### ISSUE TITLE
get_configuration_parameters_from_db_id_or_default doesnt need to retrieve the complete txm_event

### ISSUE THREAD

**Issue by kristinagalik** [mild-blue/txmatching#1017]
`get_configuration_from_db_id_or_default` now takes the whole `txm_event` of type `TxmEvent` as a parameter (but only retrieves info that can be found in `TxmEventBase`), which is in some instances computationally inefficient, and also passing huge objects between funcions

also slows down tests a bit, see `test_default_configuration`

**Comment by kubantjan** [comment]
@abragtim koukni jestli srozumitelné případně se zeptej @kristinagalik

**Comment by abragtim** [comment]
@kristinagalik 
Ve většině případů se txm_event používá i v jiných místech funkcí, které volají i get_configuration_parameters_from_db_id_or_default. Mimo testy tak to neděláme jenom v ConfigurationApi. Ale právě proto v ConfigurationApi do této funkci neposíláme celý TxmEvent, ale TxmEventBase. 
Když budeme dostávat TxmEvent.db_id a TxmEvent.default_config_id v těch funkcích, které volají get_configuration_parameters_from_db_id_or_default, tak z toho skoro nic nevyhrajeme. Správně to chápu?
<img width="1078" alt="Snímek obrazovky 2022-11-16 v 16 54 33" src="https://user-images.githubusercontent.com/25512296/202233798-f41f2b06-d877-4fc2-b5ed-71f4623c8407.png">

Trošku nechápu, proč to zpomaluje program, když txm_event neposíláme dál, než get_configuration_from_db_id_or_default. A v těch místech, kde se get_configuration_parameters_from_db_id_or_default volá, tak txm_event používáme i v jiných místech, tj. když nebudeme na vstupu vyžadovat txm_event, ale například jen txm_event_base, tak pořád v té funkci budeme muset nechat txm_event pro jiné funkce. Když máme možnost nepoužívat celý txm_event, tak posíláme rovnou txm_event_base jako to děláme v ConfigurationApi.

**Comment by kristinagalik** [comment]
a ba, ono je to tak skoro vsade, myslela som ze v testoch toho bude viac... tak asi len cisto staci napravit tie instances kde sa retirevuje zbytocne cely txmevent a nechaj tak ten parameter funkcie
