### ISSUE TITLE
Does `create_hla_typing()` works correct?

### ISSUE THREAD

**Issue by jogobeny** [mild-blue/txmatching#1022]
Does `create_hla_typing()` works correct?

**NO HLA TYPES IN HLA GROUP A**
`a = create_hla_typing(["A2", "A9", "A10"])`
![image](https://user-images.githubusercontent.com/79165095/195147231-b2069955-2c3f-4874-b1d8-10c7e27ba5a5.png)

**OK**
`b = create_hla_typing(["A2", "A9"])`
![image](https://user-images.githubusercontent.com/79165095/195147413-b3a62801-8f22-4861-a2e7-ed6e9108671a.png)

**OK**
`c = create_hla_typing(["A9", "A10"])`
![image](https://user-images.githubusercontent.com/79165095/195147510-fb89c9d3-3d12-4f69-9ebc-59e62c6b4f14.png)

**OK**
`d = create_hla_typing(["A2", "A10"])`
![image](https://user-images.githubusercontent.com/79165095/195147633-ddf58de0-3838-4f39-826d-3ab274255922.png)

**NO HLA TYPES IN HLA GROUP A**
from `txmatching/tests/patients/test_patient_parameters.py`
```
ci = create_hla_typing(
    [
        "A9",
        "A30",
        "A31",
        "B14",
        "B77",
        "DR4",
        "DR11"
    ]
)
```
![image](https://user-images.githubusercontent.com/79165095/195148667-f0ee49a5-2011-42dc-9463-3867507fd3f4.png)

**Comment by kubantjan** [comment]
This should be ok, maybe think whether something would help you to understand how it works
