### ISSUE TITLE
TAke conversion to split also from assumed serology column in dna_hla_ser table

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1048]
but to be extra careful, always when the code is taken from this column, raise a parsing issue (level warning)

**Comment by abragtim** [comment]
@kubantjan 
Chtěl bych upřesnit issue. 

Pokud správně chápu, tak cílem je, aby při parsingu z tabulky rel_dna_ser.txt ve funkci 
def parse_rel_dna_ser(path_to_rel_dna_ser: str) -> pd.DataFrame:
    ...
jsme brali hodnoty Assumed Serology a přidávali je do sloupce split_number (v pd.DataFrame) a pak ukazovali ve sloupci source něco jako "assumed". Stejně jako to děláme pro Unambiguous Serology? Jenom musím dělat raise parsing issue pokaždé, když beru hodnotu z Assumed Serology. Tak dostaneme do pd.DataFrame i assumed split hodnoty.
Tím samým přidáme do _HIGH_RES_TO_SPLIT_DICT i split hodnoty, které mají split_number z "assumed", protože už budou mimo scope .dropna()
Správně jsem pochopil zadání?

Ještě jak bychom chtěli řešit multiple values v Assumed Serology sloupci (např. 1/0)? Chceme je přidat do PARSE_HLA_CODE_EXCEPTIONS_MULTIPLE_SEROLOGICAL_CODES, ale do _HIGH_RES_TO_SPLIT_DICT nepouštět?

**Comment by kubantjan** [comment]
v zasade to chapes spravne
k tem multiple: pokud je jich tam vic (napr 2/1 atp tak to chceme pridat do toho PARSE_HLA_CODE_EXCEPTIONS_MULTIPLE_SEROLOGICAL_CODES to rikas sparvne.

jen zrovna ten priklad co jsi zvolil nesedi. v obecnosti tohle cheme resit u kodu > 0. 0 konkretne zahazujeme (viz radek 26 a 27 v rel_dna_ser_parsing.py)

**Comment by abragtim** [comment]
@kubantjan ,
Vidím, že jsou už v PARSE_HLA_CODE_EXCEPTIONS_MULTIPLE_SEROLOGICAL_CODES ručně zadáváme 
'C*04:03': ['CW4', 'CW6']. Podle tabulky rel_dna_ser.txt: 4 - je z Assumed Serology a 6 je ze Expert Assigned Exceptions. Ale pro analogická případ 'C*;04:06' to už neplatí. 

Tak bych se chtěl zeptat, jestli chceme přidávat do PARSE_HLA_CODE_EXCEPTIONS_MULTIPLE_SEROLOGICAL_CODES taky hodnoty, které mají mimo "Assumed serology" ještě i hodnotu z "Expert Assigned Exceptions"?

**Comment by kubantjan** [comment]
asi do budoucna se to da zvazovat. Ale zatim bych to nedelal. Udelej na to issue prosim, ja to proberu potom s ikemem.
