### ISSUE TITLE
Unify functions raising warning about number of antiboides and them being in high res above cutoff and function is type a

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1049]
We have two functionalities in the code that do basically the same thing:

1) in is_type_a function we are deciding based on recipient antibodies whether the recipient is type a or b.

The criterion is 
- all recipient antibodies are in high resolution
- at least one antibodiy is below cutoff
- the recipient has at least N antibodies

this way we are trying to estimate whether the user has sent as all the antibodies the user was tested for, or just some subset.

2) when checking for parsing warnings we want to warn the user in case the patient is almost type a but not quite. We want to warn if:

- all recipient antibodies are in high resolution, but all of them are above cutofff
- all recipient antibodies are in high resolution, but number is less than N and the criterion above is not true

try to deduplicate the logic as much as possible, check whether everything in readme is clear and understandable, whether the description of the warnings fits and check whether we have all the apropriate unittiest

**Comment by abragtim** [comment]
Hello. Is it for sure, that we are doing such things for donors? A found function is_recipient_type_a for recipients and duplication for this function. 
There are some steps of validating donors in do_crossmatch_type_a, but I didn't found special function for donors. And antibodies is valuable parameter mainly for recipients.

**Comment by abragtim** [comment]
I found out, that in is_recipient_type_a() we have one more deciding aspect as if antibodies split code in MULTIPLE_SERO_CODES_LIST. I don't actually understand, what does it mean and how it affects result. There is also an issue #1036 for this hack. 
I am going to rewrite exactly this function and I would like to consult, how careful I have to be with such thing. Could you write some important points about this, please, or maybe call? Is it a part of high res deciding or completely independent criterion?

Maybe it is connected with this:
"This case can handle also an antibody in the form of DP*[01:01;02:02]. It uses an algorithm that parses the specific antibodies against alpha and beta chains. In case there is some unclear case it raises a warning and requires an immunologist to check the correctness of the algorithm result."

**Comment by kubantjan** [comment]
> Hello. Is it for sure, that we are doing such things for donors? A found function is_recipient_type_a for recipients and duplication for this function. There are some steps of validating donors in do_crossmatch_type_a, but I didn't found special function for donors. And antibodies is valuable parameter mainly for recipients.

sorry, it should be recipients everywhere, only recipients have antibodies, I corrected it :)
