### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1057]
- make configurable in .env, whether there is timing of requests in logs
- log every user action clearly who did what (Again make configurable whether this is visible or not in .env)
- chceck that logging works to file and everything overall works properly - describe how exactly we are storing logs at the moment in README.

**Comment by abragtim** [comment]
Na změnu logování můžu ještě navrhnout takové vylepšení, které by možná bylo dobré udělat v tomto issue:

- možnost nastavení v .env level loggeru pri testování, aby testy běželi takhle ".......................". Díky tomuto budeme víc a rychleji reagovat na nečekané hlášky od loggeru v terminálu. Ideálně by bylo samozřejmě taky testovat logger přes assertLogs, ale budeme muset opravdu upravit všechny testy
- barevný výstup logů s level WARNING+ pro terminál (znovu nastavitelně v .env). Taková vizuální drobnost pro jednodušší orientaci v logech, možná by hodila.
- udělat configurable in .env parametr log_queries pro RequestPerformance. Teď to nastavujeme ručně v create_app.

**Comment by abragtim** [comment]
Logování do souboru funguje. Jenom složka logs se generuje v ../, tj. záleží na tom, odkud spouštíme app. Když děláme normální make run, tak logs budou mimo složku txmatching. Pokud spustíme přes IDE, tak logs budou v txmatching/txmatching/logs. Správně chápu, že chceme, aby to bylo vždycky na jednom místě (například txmatching/logs)?

**Comment by kubantjan** [comment]
> Logování do souboru funguje. Jenom složka logs se generuje v ../, tj. záleží na tom, odkud spouštíme app. Když děláme normální make run, tak logs budou mimo složku txmatching. Pokud spustíme přes IDE, tak logs budou v txmatching/txmatching/logs. Správně chápu, že chceme, aby to bylo vždycky na jednom místě (například txmatching/logs)?

@abragtim to nemuzeme mit nikdy pevne dany, zalezi na uzivateli a jeho potrebach, pripadne jak si to zrovna nastavime v docker file. Jen je dulezity abychom to meli vsude spravne a funkcni. Co me mate je ze pises ze to je v ../ a pritom pises ze kdyz to pustis v IDE bude to txmatching/txmatching/logs. Protoze moje cwd je txmatching/txmatching tak by to melo byt jen txmatcing/logs ne preci? 

pokud je to tak jak pises jinak, tak to jen napis do readme a bude to OK.
