### ISSUE TITLE
Updating some configuration fields doesnt create new config

### ISSUE THREAD

**Issue by kristinagalik** [mild-blue/txmatching#1063]
Ked sa updatne nejaky config field - napr max cycle length, tak sa vytvori novy config (a tak to aj ma byt). 

Ale su nejake fields (zatial som nasla len ze to nejde pri Minimum transplant score a Compatible blood group bonus ale bolo by dobre checknut kazdy jeden field este raz) ktore ked su zmenene tak sa updatne len ta napisana hodnota v config pop-upe, ale nevytvori sa novy config. Updatnu sa spravne az ked je aspon jeden field prepisany ktory aj novy config vytvara.

Treba toto fixnut tak aby zmena hocakeho fieldu vytvorila novy config

**Comment by kubantjan** [comment]
@kristinagalik  tohle neni frontend ale backend task ne?

**Comment by kubantjan** [comment]
Tohle je potencialne bug, docela problematicky, prozkoumat, napsat test a pripadne fixnout.
