### ISSUE TITLE
Wkhtmltopdf error in local environment

### ISSUE THREAD

**Issue by krllstdn** [mild-blue/txmatching#1083]
Pred par tydny vsechno fungovalo na tom samym systemu, ktery vyuzivam ted. Ale pak se neco rozbilo, a nevim presne co a proc.
Kdy spoustim testy spojene s reporty, nebo kdyz chci vytvorit report mam takovy error terminalu
```
 raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
Exit with code 1 due to network error: UnknownNetworkError
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback

```
Po hodinach googleni jedine k cemu jsem prisel, ze to je nejspis spojene s knihovnou `libssl`

Zkousel jsem ruzne verze `wkhtmltopdf`
- wkhtmltox_0.12.6-1.focal_amd64.deb (jak to je v README a kterou jsem pouzival pred tim nez se to rozbilo)
- wkhtmltox_0.12.6.1-2.jammy_amd64.deb (ta verze by asi vic hodila pro muj system)
- zkusel jsem jeste wkhtmltox_0.12.6-1.buster_amd64.deb ale ten se vubec nechtel naistalovat, asi kvuli tomu ze je pro Debian

Zkousel jsem take 
- libssl nejaku verze ktera se installovala spolu s wkhtmltox by default
- libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb ve spojce s libssl-dev_1.1.1f-1ubuntu2.16_amd64
- libssl3_3.0.5-2ubuntu1_amd64.deb ve spojce s libssl-dev_3.0.5-2ubuntu1_amd64.deb

Bez ohledu na konfiguraci error je vzdy  ten samy.

muj system: `Ubuntu 22.04.1 LTS`

@marazt @skalahonza @LukasForst  @kubantjan  Prosim o pomoc

**Comment by kubantjan** [comment]
a teda kdyz pustis wkhtmltopdf v terminalu, tak ti to hlasi stejnou chybu nebo ne? Zjistil jsi proc pripadne txm projekt tu chybu ma ale terminal ne?

**Comment by marazt** [comment]
A zkouseli jste to poustet v Dockeru? S timhle vam asi jinak bohuzel nepomuzu - sam bych to zkousel v nem.

**Comment by krllstdn** [comment]
Nakonec tam se neco rozbilo vic a tak ze ubuntu uz se nemohla spustit GUI. Kazdopadne problem je vyreseny - ale jsem musel preinstalovat ubuntu znova :D.
