### ISSUE TITLE
There is still a lot of logs in github pipelines when tests are running

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1118]
Ideally there should be just dots representing the tests and not clutter of warnings and info logs. This should have been fixed by #1057  but was not.

**Comment by abragtim** [comment]
- [ ] export env variable LOGGING_DISABLE_LEVEL_FOR_TESTING=ERROR in pr.yml
- [ ] one deprecation warning with assertEquals could be solved

**Comment by abragtim** [comment]
Other deprecation warnings are not in our project (should be solved by flask-restx in next version)

**Comment by krllstdn** [comment]
@abragtim A co ohledne `DeprecationWarning: 'propagate_exceptions'`? Dival sis na todle, da se to nejak resit?
