### ISSUE TITLE
Pripravit API na vyhodnoceni crossmatche pacienta

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1134]
dalsi endpoint v public api (tzn u toho uploadovaciho endpointu). 
- posle se tam typizace donora a protilatky recipienta a zpet se poslou ty typizace doplneny MFI plus typ crossmatche plus pripadne nejaky warningy. 

donor
A01:01
A02:02
recpient antibodies
A01:01 mfi 500
A02:02 mfi 1500
cutoff

-> A01:01 mfi 500 type high res

dulezity teda je vracet k TYPIZACI jestli se tam nasly protilatky. Delal bych to tak po nalezeni protilatek se zpetne doplni protilatky z antigenum

**Comment by kubantjan** [comment]
snad dostaneme z ikem brzy lepsi specifikaci, abychom se na to dobre pripravili

**Comment by krllstdn** [comment]
@kubantjan tj. output toho api musi byt (jen pro jistotu):
- list[HLAAntibodies] (crossmatched ones)
- HLAAntibodiesPerGroup (crossmatched ones)
- ParsingIssues

**Comment by kubantjan** [comment]
> @kubantjan tj. output toho api musi byt (jen pro jistotu):
> - list[HLAAntibodies] (crossmatched ones)
> - HLAAntibodiesPerGroup (crossmatched ones)
> - ParsingIssues

No moc ne. 

V zásadě co potřebujeme je ke každý typizaci donora vědět jaký jsou proti ní problematický antibodies.

Takže nějaký objekt kde budou jednotlivý typizace donora a k nim jestli jsou proti nim nějaký protilátky. 

To co posíláš ty
- List antibodies vůbec nechceme
- Hlaantibodies per group je to co stejně budeme znát tak to poslat můžeme.  Ale není to nutně potřeba
- parsing issues bych posílal.

Očividně zas teda ten můj popis issue nebyl pochopený. 

Ještě konkrétnější příklad:

donor
A1
A2
recpient antibodies
A01:01 mfi 500 cutoff 1000
A02:02 mfi 1500 cutoff 1000


Vrátit:
A1 -> antibody žádný
A2 -> antibody A02:02 mfi 1500

Něco takovýho.

**Comment by krllstdn** [comment]
dalsi endpoint v public api (tzn u toho uploadovaciho endpointu).

posle se tam typizace donora a protilatky recipienta a zpet se poslou ty typizace doplneny pripadnymy protilatkamy (tj. antigen: protilatka nebo nic) plus pripadne nejaky warningy.
donor
A01:01
A02:02
recpient antibodies
A01:01 mfi 500 cutoff 1000
A02:02 mfi 1500 cutoff 1000

-> A01:01 : nic
     A02:02: A02:02  mfi 1500 type high res

@kubantjan
