### ISSUE TITLE
Add antibody theoretical type

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1136]
Pridat typ protilatky.

budou 2 ruzny:
normal
theoretical

a pridat do AntibodyMatchTypes typ theoretical

a teoreticky funguje tak, ze kdyz je crossmatch s protilatkou typu theoretical, tak ma level theoretical a ten podobne jako undecidable se porad povoluje.

parsovani pridame az pozdeji

**Comment by krllstdn** [comment]
Ten postup je vlastne nasledujici
1. Pridat property `type` do tridy `HLAAntibody` + vytvorit nejaky enum s hodnotama 'NORMAL' a 'THEORETICAL'. Dat 'NORMAL'  jako default.
2. Pridat typ 'THEORETICAL' do `AntibodyMatchTypes`
3. Pridat check na `THEORETICAL crossmatch` pro vsechny checky v `hla_crossmatch.py` 
   1. to lze udelat tak: prejmenovat funkci`_add_none_typization()` na `add_theoretical_typization` (ta NONE typizace
       nedava smysl) a zmenit pridani NONE typyzaci na THEORETICAL
4. A napsat test, ktery overi, ze parsovani typu crossmatche THEORETICAL pro THEORETICAL protilatky funguje

@kubantjan Popsal jsem to spravne, nebo neco mi uniklo?

**Comment by krllstdn** [comment]
@kubantjan opraveno. 
Jo souhlasim, tohle fakt dela zmatek. Tak ze jeste navic prejmenovat ty funkce s 'add_**_typization' na 'add_**_crossmatch_type'?

**Comment by kubantjan** [comment]
jo
