### ISSUE TITLE
Umet si poradit i se spesl formatem hla type pri pocitani crossmatche

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1139]
Nove se v typizaci nebude posilat list typizaci ale list listu. Kazdy ten list je pak  seznam high res kodu co potencialne ten dany pacient ma. 

Tzn neco jako:
[
[A*01:02,A*01:03 .. ],
[A*02:02,A*02:03 .. ]
[B*02:03,A*02:04 .. ]
...
]

jak k tomu pristoupit:

- proste pri crossmatchi budeme resit jestli najdu nejakou vec v luminexu (mezi protilátkama na který byl pacient testovaný) pokud jo, beru to tak ze to je ten antigen co ten donor realne ma
- pokud nenajdu, prejdu do low res (vsechny ty v jednom listu by mely by stejny split rozliseni) a vezmu ze ten pacient ma typizaci split proste

pri vraceni pak vracet tu zjistenou typizaci, k ni ty protilatky, tak jak vlasnte ted.

+ jeste nove vracet summary kde bude jen pro kazdy hla typ prave 1. antibody (v pripade ze se tech protilatek najde vicero pro 1 antigen (kdyz budu mit ten antigen ve splitu) tak pak vracet jen tu protilatku ve splitu v tom summary s max mfi z tech protilatek co tam byly.

Jako prvni pripravit swagger pro tento pripad a ten si nechat schvalit mnou

edge casy:
1) najdu v luminexu vic matchu: Budeme potrebovat vracet zjistenou typizaci jako list. Typicky tam bude jedna ale nekdy vicero..
2) ke kazdymu hla typu vracet i display code (jako posilame na FE) aby vedeli do ukazovat

poznamka jeste:

v tech moznych typizacich budou i ultra high res kody (A*01:01:01:01 nebo A*01:01:01:01N tak s tim jen pocitat

**Comment by kubantjan** [comment]
cekame na zpravu z ikemu

**Comment by kubantjan** [comment]
@abragtim  updatnul jsem zadani

**Comment by abragtim** [comment]
@kubantjan. Zatím mám jednu otázku. Co je to luminex?

**Comment by kubantjan** [comment]
> @kubantjan. Zatím mám jednu otázku. Co je to luminex?

Vysvětlení v textu jsem přidal @abragtim
