### ISSUE TITLE
Improve loggin vol 2

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1144]
1) Az ted jsem poradne zkontroloval logy co mame na produkci a rekl bych ze to vubec nedela to co bylo v issue #1057 chteno.

Konkretne jsem tam chtel aby kazda akce uzivatele byla zalogovana. S jakym payloadem a co se stalo.

mame na produkci env:
```
PRODUCTION_LOGGER=true
LOGGER_DEBUG=false
SHOW_USERS_ACTIONS=true
COLORFUL_ERROR_OUTPUT=false
LOG_SQL_DURATION=false
LOG_QUERIES=false

```

Ted kdyz kouknu do logu tak tam je i cas query. Tohle niz by mela byt v tomto nastaveni jen jeden radek podle me (bez toho ze zacla a skoncila a kolik trvala)

```
{"datetime": "2023-02-07T17:12:03.836920Z", "levelname": "INFO", "name": "txmatching.web", "process": 14, "user": "88.103.234.51", "request_id": "2b16b978-d4cf-4c9c-b951-b88ad5b0e612", "method": "GET", "path": "/v1/service/status", "message": "User 88.103.234.51: Request 2b16b978-d4cf-4c9c-b951-b88ad5b0e612 started."}
{"datetime": "2023-02-07T17:12:03.868681Z", "levelname": "INFO", "name": "txmatching.web", "process": 14, "user": "88.103.234.51", "request_id": "2b16b978-d4cf-4c9c-b951-b88ad5b0e612", "method": "GET", "path": "/v1/service/status", "message": "User 88.103.234.51: Request 2b16b978-d4cf-4c9c-b951-b88ad5b0e612 took 31 ms. Method: GET /v1/service/status, arguments: {}."}

```

a teda asi obecne bych nelogoval vubec ten status endpoint ten fakt neni zajimavy, podobne taky ty jiny kde se jen getuji vlajky. to jezbytecny. to bych dal jako debugy. Vse ostatni jo, ale ty co getujou veci bez overeni neresit!. (tzn kdyz nemaji usera tak je vlastne neukladat protoze neni co logovat jako user action.

Dalsi problemy:
- logujeme v policku user ip adresu a ne usera, proc?
- zda se ze arguments policko je vzdycy prazdy a nefunguje. Treba kdyz zadam novy konfig co neexstuje tak dostanu toto

{"datetime": "2023-02-07T17:14:14.498790Z", "levelname": "INFO", "name": "txmatching.web", "process": 14, "user": "88.103.234.51", "request_id": "144bc98b-56ed-455f-9101-c8f49ad7ce60", "method": "POST", "path": "/v1/txm-event/20/configuration/find-or-create-config", "message": "User 88.103.234.51: Request 144bc98b-56ed-455f-9101-c8f49ad7ce60 took 108 ms. Method: POST /v1/txm-event/20/configuration/find-or-create-config, arguments: {}."}

ale tam argumenty jsou!

Prosim obecne si to proklikej a koukej do logu jeslti jsi schopny trackovat to jak tu aplikaci pouzivas tim ze vidis logy, ze tam neni zbytecny balast a fakt tam jsou vsechny veci.
2) Fix the way stacktrace is being written in stdout on prod. now it is extremely messy.

there are some weird formating characters like \\n and some quoatation that should probably be not there. Have a look how it is standard to put the stacktrace into json logger.

now it looks like:

'Traceback (most recent call last):\\n', '  File \"/opt/conda/envs/txmatching/lib/python3.10/site-packages/flask/app.py\", line 1820, in full_dispatch_request\\n    rv = self.dispatch_request()\\n', '  File \"/opt/conda/envs/txmatching/lib/python3.10/site-packages/flask/app.py\", line 1796, in dispatch_request\\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\\n', '  File \"/opt/conda/envs/txmatching/lib/python3.10/site-packages/flask_restx/api.py\", line 405, in wrapper\\n    resp = resource(*args, **kwargs)\\n', '  File \"/opt/conda/envs/txmatching/lib/python3.10/site-packages/flask/views.py\", line 107, in view\\n    return current_app.ensure_sync(self.dispatch_request)(**kwargs)\\n', '  File \"/opt/conda/envs/txmatching/lib/python3.10/site-packages/flask_restx/resource.py\", line 46, in dispatch_request\\n    resp = meth(*args, **kwargs)\\n', '  File \"/app/txmatching/auth/auth_check.py\", line 38, in decorated_route\\n    return original_route(*args, **kwargs)\\n', '  File \"/app/txmatching/auth/auth_check.py\", line 60, in decorated_route\\n    return original_route(*args, **kwargs)\\n', '  File \"/app/txmatching/auth/auth_check.py\", line 90, in decorated_route\\n    return original_route(*args, **kwargs)\\n', '  File \"/app/txmatching/web/api/patient_api.py\", line 94, in get\\n    lists_for_fe = to_lists_for_fe(txm_event, configuration_parameters)\\n', '  File \"/app/txmatching/data_transfer_objects/patients/out_dtos/conversions.py\", line 31, in to_lists_for_fe\\n    \\'donors\\': sorted([\\n', '  File \"/app/txmatching/data_transfer_objects/patients/out_dtos/conversions.py\", line 32, in <listcomp>\\n    donor_to_donor_dto_out(\\n', '  File \"/app/txmatching/data_transfer_objects/patients/out_dtos/conversions.py\", line 89, in donor_to_donor_dto_out\\n    donor_dto.score_with_related_recipient = scorer.score_transplant(donor, related_recipient, None)\\n', '  File \"/app/txmatching/scorers/additive_scorer.py\", line 27, in score_transplant\\n    return self.score_transplant_calculated(donor, recipient, original_donors)\\n', '  File \"/app/txmatching/scorers/hla_additive_scorer.py\", line 49, in score_transplant_calculated\\n    donor_recipient_ci = compatibility_index(\\n', '  File \"/app/txmatching/utils/hla_system/compatibility_index.py\", line 84, in compatibility_index\\n    in get_detailed_compatibility_index(donor_hla_typing, recipient_hla_typing, ci_configuration))\\n', '  File \"/app/txmatching/utils/hla_system/compatibility_index.py\", line 102, in get_detailed_compatibility_index\\n    donor_hla_types = _hla_types_for_gene_hla_group(donor_hla_typing, hla_group)\\n', '  File \"/app/txmatching/utils/hla_system/compatibility_index.py\", line 291, in _hla_types_for_gene_hla_group\\n    hla_types = _hla_types_for_hla_group(hla_typing, hla_group)\\n', '  File \"/app/txmatching/utils/hla_system/compatibility_index.py\", line 304, in _hla_types_for_hla_group\\n    return next(hla_per_group.hla_types for hla_per_group in donor_hla_typing.hla_per_groups if\\n', 'StopIteration\\n']"}}
{"datetime": "2023-01-31T08:11:18.192303Z", "levelname": "ERROR", "name": "txmatching.web.error_handler", "process": 15, "user": "176.124.185.46", "request_id": "7f812909-3489-489e-9e6f-6d19cfe91807", "method": "GET", "path": "/v1/txm-event/2/patients/configs/default", "message": "Unexpected error code returned 500, returning 500 instead"}
{"datetime": "2023-01-31T08:11:18.192552Z", "levelname": "ERROR", "name": "txmatching.web", "process": 15, "user": "176.124.185.46", "request_id": "7f812909-3489-489e-9e6f-6d19cfe91807", "method": "GET", "path": "/v1/txm-event/2/patients/configs/default", "message": "Exception on /v1/txm-event/2/patients/configs/default [GET]", "exception": {"stacktrace": "['Traceback (most recent call last):\\n', '  File \"/opt/conda/envs/txmatching/lib/python3.10/site-packages/flask/app.py\", line 1820, in full_dispatch_request\\n    rv = self.dispatch_request()\\n', '  File \"/opt/conda/envs/txmatching/lib/python3.10/site-packages/flask/app.py\", line 1796, in dispatch_request\\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\\n', '  File \"/opt/conda/envs/txmatching/lib/python3.10/site-packages/flask_restx/api.py\", line 405, in wrapper\\n    resp = resource(*args, **kwargs)\\n', '  File \"/opt/conda/envs/txmatching/lib/python3.10/site-packages/flask/views.py\", line 107, in view\\n    return current_app.ensure_sync(self.dispatch_request)(**kwargs)\\n', '  File \"/opt/conda/envs/txmatching/lib/python3.10/site-packages/flask_restx/resource.py\", line 46, in dispatch_request\\n    resp = meth(*args, **kwargs)\\n', '  File \"/app/txmatching/auth/auth_check.py\", line 38, in decorated_route\\n    return original_route(*args, **kwargs)\\n', '  File \"/app/txmatching/auth/auth_check.py\", line 60, in decorated_route\\n    return original_route(*args, **kwargs)\\n', '  File \"/app/txmatching/auth/auth_check.py\", line 90, in decorated_route\\n    return original_route(*args, **kwargs)\\n', '  File \"/app/txmatching/web/api/patient_api.py\", line 94, in get\\n    lists_for_fe = to_lists_for_fe(txm_event, configuration_parameters)\\n', '  File \"/app/txmatching/data_transfer_objects/patients/out_dtos/conversions.py\", line 31, in to_lists_for_fe\\n    \\'donors\\': sorted([\\n', '  File \"/app/txmatching/data_transfer_objects/patients/out_dtos/conversions.py\", line 32, in <listcomp>\\n    donor_to_donor_dto_out(\\n', '  File \"/app/txmatching/data_transfer_objects/patients/out_dtos/conversions.py\", line 89, in donor_to_donor_dto_out\\n    donor_dto.score_with_related_recipient = scorer.score_transplant(donor, related_recipient, None)\\n', '  File \"/app/txmatching/scorers/additive_scorer.py\", line 27, in score_transplant\\n    return self.score_transplant_calculated(donor, recipient, original_donors)\\n', '  File \"/app/txmatching/scorers/hla_additive_scorer.py\", line 49, in score_transplant_calculated\\n    donor_recipient_ci = compatibility_index(\\n', '  File \"/app/txmatching/utils/hla_system/compatibility_index.py\", line 84, in compatibility_index\\n    in get_detailed_compatibility_index(donor_hla_typing, recipient_hla_typing, ci_configuration))\\n', '  File \"/app/txmatching/utils/hla_system/compatibility_index.py\", line 102, in get_detailed_compatibility_index\\n    donor_hla_types = _hla_types_for_gene_hla_group(donor_hla_typing, hla_group)\\n', '  File \"/app/txmatching/utils/hla_system/compatibility_index.py\", line 291, in _hla_types_for_gene_hla_group\\n    hla_types = _hla_types_for_hla_group(hla_typing, hla_group)\\n', '  File \"/app/txmatching/utils/hla_system/compatibility_index.py\", line 304, in _hla_types_for_hla_group\\n    return next(hla_per_group.hla_types for hla_per_group in donor_hla_typing.hla_per_groups if\\n', 'StopIteration\\n

**Comment by kubantjan** [comment]
Plus fix the way stacktrace is being written in stdout, now it is extremely messy. (ask @abragtim  for help)

**Comment by abragtim** [comment]
@kubantjan , chápu správně, že chceme něco jako "only user activities mode", při kterém nebudeme logovat veci, které nejsou spojeny s pohybováním userů po endpointech? Ale díky tomu, že máme json logger narhuju prostě používat jej naplno, než nějak omezovat informaci v logech

Například, můžeš zkusit na STG
```
docker logs be -f --tail 20 2>&1 | jq '. | select( .user!="-")'
```
a ukáže jen logy, které jsou poslány userem, buď je autorizovaným nebo není. Po tomto PR bude možné i nastavit, abychom mohli ukazovat logy jen u autorizovaných userů, tj. které mají user email or user id. Vedu k tomu, že možná využívat ten json bude lepší, než posílat míň informací.

Navíc díky json nemusíme nějak moc řešit, že máme v logech příliš mnoho dat v jednom logu. Například lze prostě pomocí jq parsovat jen některé klíče z toho json. Hlavně kvůli tomu i chceme mít ty logy v json. Zkus tohle
```
docker logs be -f --tail 20 2>&1 | jq '. | {user: .user, msg: .message, path: .path}'
```
Jenom, že po tomto PR to bude ještě lepší, protože jsem odebral většinu informací z key message a vytvořil jsem další json klíče na to (bude ukazovat zvlášť user id, user email, user ip, sql_duration a message bude vypadat jenom jako "Request started" nebo "Request took n ms.".

Shoduje tohle s tím, jak představuješ prací s logama? Je to ok, že ty logy možná zatížím informací, kterou nejčastěji nebudeme potřebovat, ale s předpokladem, že budeme naplno používat ten json a ukazovat jen potřebnou informaci (pomocí jq https://stedolan.github.io/jq/tutorial/) pro určité situace. Json má hodně výhod a asi dává smysl  na to spolehnout.
