### ISSUE TITLE
Vlajky se nezobrazuji spravne v Edgi

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1186]
je to ale takovy divny. viz obrazek: po refreshi se to pry spravilo..

![Image](https://user-images.githubusercontent.com/24394374/231115619-9c857464-7a0d-4a35-b8a9-6c50eed197bb.png)

**Comment by kubantjan** [comment]
zkusit se pripadne poradit s @NotLubo  nebo @misslecter cim by to mohlo byt

**Comment by kristinagalik** [comment]
u mna to funguje uplne v pohode

**Comment by NotLubo** [comment]
Prosím příště screenshot s počítače a ne s kaukulačky :D Nic tam nevidno

**Comment by NotLubo** [comment]
Takže buď zavřít nebo need more info

**Comment by kubantjan** [comment]
uz se to stalo vickrat takhle jednorazove. Kdyz si to zapnuli nove po delsi dobe prave. A mas napad kdyz se jim to stane znova, co krome high resolution screenshotu? 

@NotLubo

**Comment by NotLubo** [comment]
Jako když se to stane tak nepochybuji že to bude stejná vlaječka všude (tahá se to samozřejmě jenom jednou). Ale jestli se mění mezi incidentama

**Comment by NotLubo** [comment]
No ještě jestli to zapli po delší době nanovo. Tak možná si to myslelo, že to má v cashe prohlížeče ale nemělo. Co by byla ale chyba na jejich straně. (respktive na straně edge)

**Comment by kubantjan** [comment]
ok, zkusim proste jeste zjistit vic info no.

**Comment by kubantjan** [comment]
@NotLubo  nefunguji 2 viz ten screenshot ceska a rakouska. Zkusim sesbirat vic screenshotu.

**Comment by NotLubo** [comment]
:D no tak promiň ale na to by jsem z toho screenshotu v životě nepřišel
nevím tak to ho tak zle zobrazuje jenom mě?

**Comment by kubantjan** [comment]
nn jen mam dobry oci a vim co tam ma realne byt :D
