### ISSUE TITLE
Special handling of some cases in API crossmatch

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1193]
Kdyz delame crossmatch v apicku pocitat jeden case trosku jinak nez doted a nez budeme delat v TXM.

Melo by to ve vysledku znamenat, ze Theoretical crossmatch bude mene casty. 

Kdyz mam v raw datech dvojitou protilatku (DQ[01:01,02:02] treba. A tato kombinace ma mfi pod cuttoff a pri pocitani crossmatche ma donor v typizaci presne tuto kombinaci alfa beta, tak rovnou beru ze pro dany alfa bety nema donor s recipientem crossmatch. (kdezto normalne by v tomto pripade se objevilo toto jako theoretical crossmatch)

**Comment by abragtim** [comment]
@kubantjan , správně chápu, že tohle platí jen pro high res?

**Comment by kubantjan** [comment]
ano

**Comment by abragtim** [comment]
@kubantjan , ale teď koukám a uvědomil jsem se, že při mfi < cutoff nikdy nebude theoretical antibody. Ne? 
https://github.com/mild-blue/txmatching/blob/485faabbb806c9f587e3dca52f1c2000f9692754/documentation/double_antibodies_parsing/double_antibodies_parsing_algorithm.pdf

Prostě půjdeme na začátku do dolní větve

**Comment by kubantjan** [comment]
Příklad

Donor ma DQA1*01:01, DQB1*02:02

Recipient ma namereny protilatky (cutoff 2000):
DQ[01:01,02:02] 100
DQ[01:01,03:03] 3000
DQ[01:02,03:03] 100
DQ[01:01,04:04] 100

Pak ma recipient theoretical crossmatch s MFI 100 v DQA1*01:01

I když je tam theoretical antibody dqa1*01:01 s mfi 3000

**Comment by abragtim** [comment]
> Příklad
> 
> Donor ma DQA1_01:01, DQB1_02:02
> 
> Recipient ma namereny protilatky (cutoff 2000): DQ[01:01,02:02] 100 DQ[01:01,03:03] 3000 DQ[01:02,03:03] 100 DQ[01:01,04:04] 100
> 
> Pak ma recipient theoretical crossmatch s MFI 100 v DQA1*01:01
> 
> I když je tam theoretical antibody dqa1*01:01 s mfi 3000

Díky
