### ISSUE TITLE
Prozkoumat nastroj easy hla

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1201]
Prozkoumat jak slozite by bylo do naseho programu nastroj

 [Easy-HLA (univ-nantes.fr)](https://hla.univ-nantes.fr/index.php#), je sada nastroju z nichž nejvíc by nás mohl zajímat HLA-upgrade, což je nástroj, který dokáže podle frekvencí haplotypů v NMDP populaci s určitou pravděpodobností z low res typizace dopočítat high res (bohužel zatím pouze pro alely HLA- A,B,C,DRB1,DQB1). To by se mohlo hodit pro dopočítávání pacientů a dárců, kteří mají jen low-res.

vice na tom webu nebo v prilozenem clanku

Fungovat by to melo v mych naivnich predstavach tak, ze dostanu pacienta v low res, prozenu to timto toolem a budu mit high res typizaci.

nástroje jsou volně dostupné i s kódy ([CRTI - Team 3 / Easy-HLA · GitLab (univ-nantes.fr)](https://gitlab.univ-nantes.fr/crtiteam5/easy-hla)) Matej roder rikal, ze autori jsou hodne pratelsky, takze s libovolnymi dotazy jim muzeme napsat/jim zavolat.

[Geffard 2020 Easy-HLA.pdf](https://github.com/mild-blue/txmatching/files/11343815/Geffard.2020.Easy-HLA.pdf)

**Comment by abragtim** [comment]
# První pohled:

## Možné problémy
- [ ] Kód je napsán na PHP ve francouzštině (žádný z těchto jazyků neznám)
- [ ] Žádné README, jenom dokumentace o tom, jak používat jejich web
- [ ] Odpovědi na požadavky asi dostáváme v HTML. Alespoň to tak vidím přes browser

## Příklad použití

Vstup:

![Image](https://user-images.githubusercontent.com/25512296/235316185-dd313b42-40f5-42a9-a26b-9eb568ecb4c3.png)

Výstup:


![Image](https://user-images.githubusercontent.com/25512296/235316193-163a1088-e033-46d8-927b-8684063f6979.png)


Nejpravděpodobnější kombinace (1. řádek na výstupu) má post-probability 48.6, což odpovídá accuracy cca 70% (podle grafu ve výzkumu)

**Comment by abragtim** [comment]
Next steps:

1. Dostat realná data z TXM v HIGH RES a podívat se, jak je bude předpovídat Easy-HLA (budeme zadávat jen low res část těchto dat)
2. Zvážit možnost vlastní implementace tohoto algoritmu. Může to mít velký potenciál, že by se dávalo smysl mít to jako část TXM s možností udržování 
3. ....

**Comment by abragtim** [comment]
### Jak to bude fungovat v případě TXM, tj. low res -> high res?
Funguje to tak, jak očekáváme. Můžeme dostávat výsledky jak s vysokou post probability (cca 90), tak i s nižšími (20-30). 
Vcelku predikuje to high res docela dobře. Často se stává, že nemá jistotu jenom u některých HLA, když ve všech možných výsledcích hlavně se mění jenom tato HLA a ostatní jsou pevné skoro ve všech případech

**Comment by abragtim** [comment]
Licence u database, kterou používá Easy HLA: https://frequency.nmdp.org/jsp/licenseAgreement.jsp#

**Comment by kubantjan** [comment]
@abragtim  dopise kratky textik a nekdy v tydnu si zavolame nad tim

**Comment by kubantjan** [comment]
@abragtim doplnit otevrenou otazku plus pripadne neco co jeste je k tomu uzitecny co jsi zjistil a nekde visi v konzerzaci nebo v mejlu nebo tak.

**Comment by abragtim** [comment]
Prošel jsem tu studii ještě jednou a myslím si, že jsem úplně pochopil, jak to konečně funguje. Jenom, podle mě, je tam důležitý překlep, a proto bychom pro ujištění, že z biologické strany všechno taky chápeme, zeptal bych se na Matěje s jedinou otázkou:

"Jaké možné kombinace diplotypů (haplotypnich par) musíme uvažovat (například homozygoty nechceme, protože jsou nepravděpodobné)? Příklad logiky, jak je tvoříme na
Aa ~ Bbβ ~ Cc? U nějakých dalších?"

**Comment by kubantjan** [comment]
@abragtim  doformulovat otazku pak posleme na mateje

**Comment by abragtim** [comment]
https://github.com/mild-blue/txmatching-hla-frequencies-lib/issues/2#issuecomment-1614254673
