### ISSUE TITLE
Udělat lepší example v swagger u do-crossmatch

### ISSUE THREAD

**Issue by abragtim** [mild-blue/txmatching#1213]
Chceme mít skoro skutečný example, jak to vypadá v případě response 200, tj. ne "string", ale skutečný příklad se validním počtem antigenů pro jednoho člověka a pridat tam i nejaky priklad s hranatou zavorkou

**Comment by kubantjan** [comment]
toto udelejme jako prvni step toho tasku s pravdepodobnosti

**Comment by kubantjan** [comment]
tady zavru
