### ISSUE TITLE
Naplánovat architekturu nového balíčku pro TXM, který bude komunikovat s NMDP databází

### ISSUE THREAD

**Issue by abragtim** [mild-blue/txmatching#1214]
Chceme implementovat easy HLA (viz #1201), tak je potřeba rozmyslet, jak to bude fungovat, udělat issues a deadlines. Takový report pak poslat v IKEM na schválení

Pak díky tomu budeme umět pro split určovat pravděpodobnost crossmatch, což potenciálně muže snížit počet positive jenom kvůli low res.

**Comment by kubantjan** [comment]
duplicate
