### ISSUE TITLE
Split v summary antibody

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1230]
- Kdyz mam split prevod protoze vsechno bylo infrequent tak v summary antibody taky uvest jen split a spocitat prumer z pozitivnich, nebrat tam max.

**Comment by abragtim** [comment]
Pokusím se tady zformulovat, jak bude fungovat summary antibody po tomto PR

### Case 1: všechny assumed hla types jsou infrequent se stejným split -> byly převedeny na stejný split
Do summary dáme ten SPLIT s průměrem MFI > cutoff

### Case 2: mezi assumed hla types jsou několik frequent v high res a mají stejný split
Do summary dáme jejich SPLIT + průměr MFI > cutoff  + parsing issue (antibodies against A2 might not be DSA, for more see detailed section)

### Case 3: mezi assumed hla types je jenom jeden frequent v high res a má MFI > cutoff
Do summary dáme HIGH RES toho jednoho frequent

### Case 4: mezi assumed hla types je jenom jeden frequent v high res, ale má MFI < cutoff
Do summary dáme null + parsing issue (UNLIKELY CROSSMATCH)

### Case 5: všechny assumed hla types json infrequent, ale mají různý split -> byly převedeny na několik splitů
_TODO: Do summary dáme co? Co máme dat, když mám různé splity s MFI > cutoff (chápu, že MFI bude průměr, ale jaký z těch kódů vzít, když už nemůžu jít ze splitu na level níž)?_


@kubantjan , mohl bys, prosím, doplnit case 5?

**Comment by kubantjan** [comment]
CASE 4 pak budeme v issue #1232 jeste upravovat, ale tady urcite nepatri parsing issue unlikely crossmatch tohle neni duvod davat jakykoliv parsing issue, je uplne ok tam mit proste null

**Comment by kubantjan** [comment]
CASE 5 a 6 vysvetluju prave v komentari. Tom nahore. Co na tom neni jasny?

CASE 6 presne odpovida popisku:
> kdyz mam pripad ze mam v assumed nekolik high res res kodu co jsou frequent (napriklad A02:01 a A02:02) a pro A02:01 mam protilatku s mfi>cuttof a pro A02:02 ne. co dat do summary?
split code A2 mfi 5000 (kdyby bylo tech kodu pozitivnich pro frequent vic, tak jejich prumer)

**Comment by abragtim** [comment]
> CASE 5 a 6 vysvetluju prave v komentari. Tom nahore. Co na tom neni jasny?

Píšeš, že musíme vzít průměr těch MFI, ale co dát za kód.
Například
```
assumed hla types = [A1, A2]
antibody matches = [A1:01 s mfi 3000 > cutoff, A2:01 s mfi 4000 > cutoff]
```

summary tim pádem má být
```
summary_antibody = {
    'hla_code': "Jaký? A1 nebo A2? Nebo bude to list, kde máme oba [A1, A2]",
    'mfi': 2500
}
```

**Comment by kubantjan** [comment]
> > CASE 5 a 6 vysvetluju prave v komentari. Tom nahore. Co na tom neni jasny?
> 
> Píšeš, že musíme vzít průměr těch MFI, ale co dát za kód. Například
> 
> ```
> assumed hla types = [A1, A2]
> antibody matches = [A1:01 s mfi 3000 > cutoff, A2:01 s mfi 4000 > cutoff]
> ```
> 
> summary tim pádem má být
> 
> ```
> summary_antibody = {
>     'hla_code': "Jaký? A1 nebo A2? Nebo bude to list, kde máme oba [A1, A2]",
>     'mfi': 3500
> }
> ```

vezmi ten s nejvyssim mfi. a v tomto pripade dej A2. S tim ze tam bude ta hlaska s tim DSA, ktera ted neni na 100% presna, ale prozatim to takto staci. Na tom jeste zaiterujeme.

**Comment by kubantjan** [comment]
Doptam se jeste mateje, ale zatim takto

**Comment by kubantjan** [comment]
@abragtim  jeste jsem se doptal mateje a vezmi ten s tim vyssim mfi. Co se tyce textu tak tam bude potreba vyhodnoti case
1) neco ma mfi pod neco nad, pak pouzivej to s tim DSA
2) vse ma nad pak pouzivej to co matej pise nize.

MAtej konkretne pise na otazku:
kdyz mam pripad ze mam nekolik high res res kodu co jsou frequent a maji ruzny splity (napriklad A*02:01 a A*01:01), a*01:01 ma mfi 4000 a a*02:01 mfi 5000 Co chce pak uzivatel videt?
NApada me: A2 mfi 4500 + text: the crossmatch estimation was complex in this case for more see detailed section


Myslím, že pokud typizace proběhne správně, tak by se to nemělo stát, že by měl 2 různé frequent splity, proti kterým by byli v Luminexu kuličky, nicméně asi by to pak chtělo vypsat to vyšší MFI a hodit warning: Ambiguity in HLA typization, for more see detailed section.

**Comment by abragtim** [comment]
> 

@kubantjan , v tomhle kontextu "něco" znamená split kód pro summary nebo antibody z listu antibody matches, 
tj. spočítáme průměr MFI pro A1, průměr MFI pro A2. Pokud jsou obě nad, tak "Ambiguity in HLA typization, for more see detailed section.", jinak DSA.

Nebo pokud nějaká protilátka u A2 má MFI < cutoff, tak dáme DSA. Pokud všechny protilátky mají MFI > cutoff, tak dáme "Ambiguity in HLA typization, for more see detailed section."

?

**Comment by abragtim** [comment]
@kubantjan , když teď koukám na CASE 4 a CASE 6, tak se mi zdá, že musí být transformována formulace

Case 4: proti assumed hla types nejsou žádné protilátky (to se má vyřešit v rámci #1232 )
Case 6: mezi assumed hla types jsou několik frequent v high res a mají různý split + antibody matches není prázdný

Správně? Předpokládám, že Cases 1-3 a 5-6 mají vždycky alespoň jednu protilátku s MFI > cutoff, pokud tomu tak není, tak bude to Case 4, který se řeší v rámci #1232 , protože bychom potřeboval mít informaci o protilátkách s MFI < cutoff, které v objektu AntibodyMatchForHLAType nemám

**Comment by abragtim** [comment]
@kubantjan , podle jakého principu chceme volit match_type v summary?

**Comment by kubantjan** [comment]
A1

- `A*01:01` mfi 3000
- `A*01:02` mfi 1000

**Comment by kubantjan** [comment]
ukazuju vzdy highest match a logika je ze vzdy resim jen crossmatch protilatky na tom nejvyssim levelu.
