### ISSUE TITLE
Promyslet jak by mohlo fungovat v crossmatch api propojeni s tabulkama frekvenci

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1234]

**Comment by kubantjan** [comment]
https://github.com/mild-blue/txmatching/issues/1201

**Comment by kubantjan** [comment]
@abragtim  pripravuje navrh, ma nejaky 3 zpusoby, ktery probere s @jakubmonhart a sem napisou potom zaver z tech diskusi

**Comment by kubantjan** [comment]
cilem je teda mit kdyz dostanu typizaci donora s is_frequent, tak ke kazdymu kodu krome is_frequent mit i population frequency

**Comment by kubantjan** [comment]
jen pro zajimavost, Tady je ta publikace, na základě které jsou alely brány jako frequent https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3634360/

**Comment by abragtim** [comment]
1. Zeptat se IKEM na potential hla typing, co je to?
