### ISSUE TITLE
Report pro Xenii

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1254]
1) How many pairs of the joint pool are ABOi, HLAi, or both
 ABOi and HLAi?
- pro aktualni beh
- pro vsechny behy dohromady (vybrat manualne ty realny)
 2) What is the fraction of the pairs in the joint pool that are
 highly-sensitized (cPRA>90%) and very highly-sensitized (cPRA>97%)?
 If you could provide average values or a table with data for each
 separate matching run, it would be a great help!
3) Could you specify which criteria are used to identify which
 exchanges will proceed for the transplantation? How do you apply
 these criteria, e.g. is it sequential, or are the weights provided
 for each transplants based on some characteristics (if so, which)?

**Comment by jakubmonhart** [comment]
@kubantjan Pochopil jsem to tak ze chci resit to cPRA, ale to se tyka jenom te otazky 2. Co ta otazka 1, tu mam taky vyresit?

**Comment by jakubmonhart** [comment]
No a z tvoji konverzace ve slacku si vlastne nejsem jisty jestli s tim mam cekat nez Matej nejak specifikuje ten vypocet cPRA nebo to udelat tak jak to mame v txmatching nachystane.

**Comment by kubantjan** [comment]
tak jak to mame v txm nachystane to urcite delat nechceme. Chceme to delat nejak jinak a to bud nam musi rict matej, nebo si to musime vygooglit my..

**Comment by kubantjan** [comment]
jeste jsem jim kolem toho napsal, do te doby s bodem 2. jeste pockejme. Naopak te poprosim se povenovat bodum 1. a 3. ty by prave i bez cPRA melo jit v pohode vyresit (ta 1. je to co jsme diskutovali na standupu prave. A 3. by asi melo jit trosku vykopirovat readme proste)

**Comment by kubantjan** [comment]
@jakubmonhart

**Comment by jakubmonhart** [comment]
@kubantjan  Pro tu 1. chceme není mi stoprocentně jasné co je tam myšleno tím párem z joint pool. Chceme tu statistiku vyjet pro páry tak jak jsou do txm přidávány (tedy donor-recipient) nebo i pro všechny možné páry (prostě všechny kombinace donor - recipient ktere lze namixovat)?

**Comment by kubantjan** [comment]
donor-related recipient pouze
@jakubmonhart

**Comment by kubantjan** [comment]
tak bod 2. udelame my.

asi to zkusime pres SOAP requesty na etrl.org. Na to ale jeste potrebujeme credentials. Tak uvidime. To ted dela ikem

Hello,
for research purposes in Czech transplant programme we would like to calculate vPRA in batches and for that purpose we would like to ask for credentials for ETRL batch calculator as described in the document https://etrl.org/Manuals/ETRL%20batch%20calculator%20user%20guide%20English%20V3.0.pdf
poslal bych to na toho [IHB.ICT@lumc.nl](mailto:IHB.ICT@lumc.nl) plus tam dal do kopie [etrl@eurotransplant.org](mailto:etrl@eurotransplant.org)

(navod pripadne tady https://www.youtube.com/watch?v=2FDNQ5w1tDY)

**Comment by jakubmonhart** [comment]
@kubantjan  Petr Raska na slacku pise "Honzo mohl bych poprosit o počty jedná se pouze o pacienty CZ, AT a IS" .. vezmu tedy vsechny produkcni eventy a budu brat jenom pacienty z CZ AT IS (nebo se chci divat jenom na ty eventy 2021-01-CZE-ISR-AUT, ... ? )
