### ISSUE TITLE
Dostavame error co se tyka invalid codes na demu

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1258]
Nemu v txm eventu 8 (slovaci) dostavame error ze {"datetime": "2023-07-25T09:49:57.673716Z", "levelname": "WARNING", "name": "txmatching.web.error_handler", "process": 15, "user_ip": "176.124.185.46", "request_id": "6a70e0fa-3c41-43db-8faf-f5669f3322fc", "method": "GET", "path": "/v1/txm-event/8/patients/configs/default", "message": "KeyError: - <HLAGroup.INVALID_CODES: 'INVALID_CODES'>", "arguments": {"include-antibodies-raw": ""}}

asi si stahnout ty data k sobe, pustit lokalne a oddebugovat co se tam deje

v ramci tohoto stale vidim issue ze tam neni full stack trace u tohoto erroru coz pak zhorsuje debugging na to take mrknout pripadne (nebo udelat dalsi issue)

**Comment by jakubmonhart** [comment]
@kubantjan  Donor s db id 1153 a recipient s db id 1033 mají invalid codes v hla typing. Jsou related.
Donor:
```
{"hla_group": "INVALID_CODES", "hla_types": [{"code": {"broad": "C*02:01", "split": "C*02:01", "high_res": "C*02:01"}, "raw_code": "C*02:01"}, {"code": {"broad": "C*12:01", "split": "C*12:01", "high_res": "C*12:01"}, "raw_code": "C*12:01"}]}]}
```

Recipient:
```
{"hla_group": "INVALID_CODES", "hla_types": [{"code": {"broad": "C*12:01", "split": "C*12:01", "high_res": "C*12:01"}, "raw_code": "C*12:01"}
```

Při nahrávání pacientů na frontend se volá `AllPatients` endpoint -> `to_lists_for_fe` -> `donor_to_donor_dto_out` -> `score_transplant` -> `score_transplant_calculated` -> `compatibility_index` -> `get_detailed_compatibility_index` -> `_get_ci_for_recipient_donor_types_in_group` -> `_match_through_high_res_codes` -> `_match_through_lambda` -> `ci_configuration.compute_match_compatibility_index` -> `self.hla_typing_bonus_per_groups_without_dp_dq[hla_group]` ... a tady to padá, protože pro pro HLAGroup.INVALID_CODES není ten bonus definovaný:

```
 @property
    def hla_typing_bonus_per_groups_without_dp_dq(self):
        return {
            HLAGroup.A: 1,
            HLAGroup.B: 3,
            HLAGroup.DRB1: 9,
            HLAGroup.CW: 0,
            HLAGroup.OTHER_DR: 0
        }
```

**Comment by kubantjan** [comment]
ok a proc parsujeme kod  C*02:01 ve splitu take na  C*02:01 kdyz napriklad kod C*01:02 zparsujeme spravne? rozhodne by se nemelo stat ze v split a broad kodech budeme mit format C* to je jeden bug

Krome toho tedy i to, ze bychom si meli samozrejme i s invalid kody poradi.

@jakubmonhart  mas na to jeste dnes prostor se kouknout? Nebo to mam predat?

**Comment by jakubmonhart** [comment]
> @jakubmonhart  mas na to jeste dnes prostor se kouknout? Nebo to mam predat?

Jojo, za chvili jdu na to.

**Comment by jakubmonhart** [comment]
@kubantjan  `C*02:01` a `C*12:01` nejsou v `HIGH_RES_TO_SPLIT_OR_BROAD`, protože není v `ALL_NON_ULTRA_HIGH_RES_CODES` .. to se parsuje z `rel_dna_ser.txt`, kde `C*02:01` ani `C*12:01` není (začínáme až s `C*02:02` a `C*12:02`).

> Krome toho tedy i to, ze bychom si meli samozrejme i s invalid kody poradi.
Jakože by invalid kode měl projít skrze ten score computation bez erroru .. proste ho budeme ignorovat?
