### ISSUE TITLE
Api na pocitani CPRA

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1260]
Pridat APi na ktery se posle recipient (jen jeho protilatky) ve stejnym formatu jako jsme ted zvykly a to se zparsuje jak jsme zvykly a pak se vrati zparsovany protilatky recipienta plus cpra.

melo by to kopirovat logiku kterou delal @jakubmonhart v #1254 cpra pocitat stejne jak tam a vsechno v podstate je jen o preklopeni. Pridat tenhle endpoint asi k tomu crossmatch api, taky public stejne jako tamten.

**Comment by abragtim** [comment]
@kubantjan , ahoj. Lze pushnout s loginem a heslem od https://etrl.org/, které je na bitwardenu? Nebo bude potřeba, aby se každý uživatel přihlašoval sám?

**Comment by kubantjan** [comment]
> @kubantjan , ahoj. Lze pushnout s loginem a heslem od https://etrl.org/, které je na bitwardenu? Nebo bude potřeba, aby se každý uživatel přihlašoval sám?

dejme to prosim do .env promenne
