### ISSUE TITLE
Nahrat data slovakum

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1273]
Dobry den pan inzinier,
chcela by som Vas velmi pekne poprosit o nahratie výsledkov z Luminexu u nasej pacientky BI_1971_KE, ktorú by sme chceli s jej inkompatibilnou darkynou zaradit medzi nase pary. 
Dakujem Vam za ochotu a pozdravujem
Danica Ševcová

data poslali emailem

**Comment by kubantjan** [comment]
@jakubmonhart https://drive.google.com/drive/folders/1g2GTJc5HKhnt_qNXPpWmanR1tePJlbN9

**Comment by kubantjan** [comment]
@jakubmonhart to je hotovo?

**Comment by jakubmonhart** [comment]
Přeposlal jsem ti poslední mail co jsem dostal. Čekal jsem ještě nějakou reakci, ale možná je vše ok, tak můžeme zavřít.
