### ISSUE TITLE
Prozkoumat issues s endpointem pro kadavery od mateje

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#1274]
Viz https://dciikem.slack.com/archives/C05F3FQQEBS/p1722949048725479

- [x] V prvni fazi zkusit zreprodukovat, pochopit o co jde. a pak si s @kubantjan zavolat
- [x] Fixnout bug, ze kdyz je antibody mixed a ma vic positive (to co testujeme v testu). Pokud jsou protilatky jsou vysvetleny tak spocitat prumer z negativnich  ( #1276 )
- [x] Připravit testy k bugu spojeným s CW7 (https://github.com/mild-blue/txmatching/pull/1277)
- [x] Fix CW7 bug (https://github.com/mild-blue/txmatching/pull/1277)
- [x] Obnovit rel_dna_ser.txt (#1278 )

**Comment by abragtim** [comment]
1. Co se tyče DPA1 HIGH_RES_MATCH_ON_SPLIT_LEVEL

- recipient má
 		{

			"name": "**DP[01:04**,18:01]",
			"mfi": 19088,
			"cutoff": 2000
		},
		{
			"name": "**DP[01:05**,03:01]",
			"mfi": 20918,
			"cutoff": 2000
		},
		{
			"name": "**DP[01:05**,18:01]",
			"mfi": 20625,
			"cutoff": 2000
		},
		{
			"name": "**DP[01:05**,28:01]",
			"mfi": 2253,
			"cutoff": 2000
		},

- donor nemá HLA jako u recipienta, a proto bereme jako SPLIT
```python
        # Try to leave only those HLA types that have their codes among antibodies
        maybe_assumed_hla_types = [assumed_hla_type for assumed_hla_type in potential_hla_types
                                   if assumed_hla_type.hla_type.code in antibodies_codes]
        if maybe_assumed_hla_types:
            append_to_assumed_hla_typing_with_frequency_check(maybe_assumed_hla_types)
            continue

        # If there are none found, then it's not a problem.
        # Convert the entire potential HLA type to low resolution.
        assumed_hla_typing.append(_convert_potential_hla_types_to_low_res(potential_hla_types))
```

**Comment by abragtim** [comment]
> Jak by mělo být správně? Na konci tohoto cyklu zkontrolovat, jestli jsou všechny a ty které nejsou spočítat jako průměr negativních?

V [dokumentaci](https://github.com/mild-blue/txmatching/tree/master/documentation) máme napsáno

> In summary, if we encounter this positive and mixed chain case where the mixed chain has several positive representations among all the antibodies, we expect to parse the mixed chain through other antibodies.

Tento předpoklad se v tomto případě nesplní, když budeme dostávat jen pozitive + mixed nebo negativní případy (viz schéma nahoře). Nejspíš chceme, aby na konci tohoto cyklu jsme naparsovali všechny, tak za mě asi mean negativních dává smysl. Jakoby

1. Pozitivita MFI je způsobena jinými chains u těchto protilátek, a proto ty které jsou nad cutoff neuvažujeme
2. Naparsujeme jako mean negativních. To samé děláme, když je pozitivní jenom v jedné antibody

> This mixed chain DPB1*02:02, which has positive representation just in this antibody DP*[01:03;02:02] (there aren't any other antibodies where this chain has positive MFI), is parsed as
> 
> DPB1*02:02, MFI 100 (average negative MFI), cutoff 2000

**Comment by kubantjan** [comment]
Tak to nejak ctu. 

kde mame to schema? Rad bych tam nejaky veci upravil/vylepsil @tim

**Comment by abragtim** [comment]
> Tak to nejak ctu.
> 
> kde mame to schema? Rad bych tam nejaky veci upravil/vylepsil @abragtim

@kubantjan , https://github.com/mild-blue/txmatching/tree/master/documentation/double_antibodies_parsing

**Comment by kubantjan** [comment]
No melo by to fungovat tak, ze kdyz je antibody mixed tak by bud:

a) vsechny hodnoty nad cutoff jsou vyreseny ze jsou pozitive ty druhy z dvojicky a pak bych mel vzit ze je negative z prumeru tech negativnich.
b) nejaka hodnota nad cutoff neni vyresena ani tak -> pak teda mam nejaky u kterych to nedokazu rozhodnout. to bychom meli upozornit a zahlasit, ze je takovy pripad a pro kazdou takovou dvojicku dat nejaky warning.

**Comment by abragtim** [comment]
@abragtim , udělat unittest, který bude padat  a přidat komentář jak by měl podle mě fungovat

**Comment by kubantjan** [comment]
@abragtim pripsal jsem ti tam task nahoru do description.

**Comment by kubantjan** [comment]
Moje pochopeni je teda, ze co se mohlo stat je bud ze nejaka negativni protilatka se nam neukazala, nebo jsme neudelali to double antibody a theoretical nekdy.

tzn budto se zbytecne nenasel nejaky chain, ptze jsme nevedeli o negativnosti protilatky a tak jsme presli na split, nebo dokonce jsme dali undecidable

v druhem pripade jsme teda nekdy nasli par, u kteryho jsme meli dat warning ze tam je theoretical crossmatch ale my jsme ho nedali.. 

Oboji je problematicky, ale kriticky.

**Comment by abragtim** [comment]
@kubantjan 

> Fixnout bug, ze kdyz je antibody mixed a ma vic positive (to co testujeme v testu). A to tak, ze kdyz jsou ty positive nevysvetleny, tak z toho udelat klasicky double s theoretical, pokud jsou vysvetleny tak spocitat prumer z negativnich

Co znamená vysvětlený / nevysvětlený? Nevysvětlený = existuje mixed + mixed chains případ? Vysvětlený = všechny jsou buď mixed + pozitive nebo mixed + negative případy (tj. to na co jsem připravil test)?

Z mé strany nefunguje jenom případ, když jsou vysvětlené

**Comment by kubantjan** [comment]
ano mas pravdu nefunguje jen a). sorry, takze fixnout jen to @abragtim

**Comment by kubantjan** [comment]
Tzn matejovi pisu:

mame tam bug. Ze nekdy spatne neuvadime negativni protilatku. (je to presne ten pripad ktery popisujes s tim DPA1*01:03) prozkoumali jsme to dukladne okolo a tohle je skutecne jediny problem. Tenhle bug byl i v TXM jako takovem. Coz znamena ze se nekdy mohlo stat, ze nejakou protilatku jsme neuvedli jako negativni. Takze jsme mohli pak zakazat nejakou vymenu protoze jsme nenasli negativni protilatku proti donorove typizaci a tak jsme presli do splitu, kde to treba mohlo byt pozitivni. 

Ted to opravujeme, jak to vypada s touhle vymenou? Dava ti smysl to jeste pohrotit aby to tam bylo fixnute?

**Comment by abragtim** [comment]
> mame tam bug. Ze nekdy spatne neuvadime negativni protilatku. (je to presne ten pripad ktery popisujes s tim DPA1*01:03) prozkoumali jsme to dukladne okolo a tohle je skutecne jediny problem. Tenhle bug byl i v TXM jako takovem. Coz znamena ze se nekdy mohlo stat, ze nejakou protilatku jsme neuvedli jako negativni. Takze jsme mohli pak zakazat nejakou vymenu protoze jsme nenasli negativni protilatku proti donorove typizaci a tak jsme presli do splitu, kde to treba mohlo byt pozitivni.
> 
> Ted to opravujeme, jak to vypada s touhle vymenou? Dava ti smysl to jeste pohrotit aby to tam bylo fixnute?

@kubantjan , toto je za mě super

**Comment by kubantjan** [comment]
K tomu c muj pohled:

1) databazi aktualizujeme, abychom tam meli ty nove Ccka. V ten moment by se to melo uklidit.
2) kdyz nejaky kod mame jako unexpected tak potom ho mame jako frequent. Coz je spatne chovani, meli bychom tam proste prenest tu jeho frequency, to je bug. 
3) Kdyz mame kod unexpected nemeli bychom probublavat slpit a tak aten high res kod ale mit to null
4) v assumed hla types by se nam u C*01:01 nemel ztratit high res kod nevim proc se to deje

co myslis? Tyhle veci bych fixnul. Pokud souhlasi
poprosim te k bodum 2 - 4 napsat test

**Comment by abragtim** [comment]
> 4. v assumed hla types by se nam u C*01:01 nemel ztratit high res kod nevim proc se to deje

asi si myslíš C*07:01? Tady je ztratit high res kód z mého pohledu ok. Převádíme do SPLIT, protože není žádný z těchto CW7 v high res u recipienta, a proto zkoušíme provést crossmatch ve SPLIT. Ideálně by mezi CW7 měl zůstat jenom ten SPLIT kód, jenom jsou tam spoustu těch dalších, které nemáme v datech, a proto nemůžeme říct, že mají SPLIT CW7

> 3. Kdyz mame kod unexpected nemeli bychom probublavat slpit a tak aten high res kod ale mit to null

jo, ideálně by to tak mělo být, ale ještě zkontroluju, co tato logika ovlivňuje. Pokud to bude nějak složité na opravu v běžném TXM, že se na tento předpoklad nějak spoléhá, tak bych to nechal a vyřešil bych situaci s frequent / infrequent přímo v tom crossmatch api a tuto logiku bych nechal. Zkratka souhlasím, ale nedokážu říct nakolik to bude složité / invazivní, ještě prozkoumám

**Comment by kubantjan** [comment]
4. ok, rozumim souhlas.

**Comment by abragtim** [comment]
@abragtim 

- prozkoumat #1224
- pridat komentar pro volbu isfrequent
