### ISSUE TITLE
Represent blood by enum

### ISSUE THREAD

**Issue by tomaspavlin** [mild-blue/txmatching#477]
# 🩸 Represent blood by enum

## Background
Currently, we store blood type as TEXT in DB and converting blood from db model to typed dataclasses is not working properly. 

## Needs to be done
We want to use enum for storing blood instead. This needs to be changed in the following db columns:

`DonorModel.blood`
`RecipientModel.blood`
`RecipientAcceptableBloodModel.blood_type`

This will also require to change few tests. Also please verify, that blood type conversion is working properly.

**Comment by kubantjan** [comment]
@kristinagalik  tohle se teda muze zavrit?
