### ISSUE TITLE
Make ILP solver more robust for large number of patients

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#499]
Add better formulation of the ILP problem for the cases when the chain and cycle length is small.

Use article: 
https://dl.acm.org/doi/abs/10.1007/s10878-015-9932-4

(Idea thanks to Felipe Subiabre)

**Comment by kubantjan** [comment]
Due to:

Too low threshold for max number of ILP dynamic constraints
Adding max number of countries in round makes number of added dynamic constraints raise too much
Confusing stuff written when the run does not finish (there is error window, but still written no matchings found)
increase the max constraint number
some optimalizations in the dynamic constraint universe
use some other quicker approach from the article
use Gurobi
???

**Comment by krllstdn** [comment]
is it still relevant?

**Comment by kubantjan** [comment]
no, it is not
