### ISSUE TITLE
More match type logic

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#531]

**Comment by kristinagalik** [comment]
@kubantjan len checkovacia otazka - ono to skor asi bolo myslene pre `AntibodyMatchTypes` nez pre `MatchType`, nie? lenze potom tie dve posledne odrazky `HIGH_RES_WITH_SPLIT`, `HIGH_RES_WITH_BROAD` vedia byt asi aj pre `MatchType` pre zistovanie CI ci to netreba riesit?

**Comment by kubantjan** [comment]
@kristinagalik  plese write in english, this was due to historical reasons in czech, but we want to avoid that from now on.

+ as I am reading it again, I think it makes sense to rewrite it a bit, I will do that below

**Comment by kubantjan** [comment]
At the moment we have the following antibody match types:

High res - match at high res level, the highest and the most sure type of match
  -  both typization and antibody is in split resolution and there is match
Split - match at split level. Either:
  - one of them was in higher res and the other in split
  - antibodies are all in high res, but for given typization the test was not done and there is match on split level
Broad - similar to split

 
This is not good enough. Plus there are some issues:
1)  both typization and antibody is in split resolution and there is match
make it split resolution, not high res as it is now. 
2) Add other categories:
Split_from_high_res: 
  - one of them was in higher res and the other in split
  - antibodies are all in high res, but for given typization the test was not done and there is match on split level
Indecisible:
   - antibody exists against a typization group that the donor was not typizised for. 


potom v tech kategoriich allowed crossmatch types predelat split_and_broad na to aby povolovat jen broad nebo split_with_high_res (ne split samotnej)
