### ISSUE TITLE
More speedup

### ISSUE THREAD

**Issue by tomaspavlin** [mild-blue/txmatching#540]
Už jsme udělali speedup v https://github.com/mild-blue/txmatching/pull/537, ale je pár možností, jak to ještě zrychlit:

- Co trvá dlouho, tak je získání txm event z db. Jsou tam uložené dost velké jsons, které bychom trochu změnšili vyřešením https://github.com/mild-blue/txmatching/issues/507. Jinak myslím, že dokud budeme tahat tolik dat z db, bude to prostě trvat dlouho.
- Na stránce matchings se provolají po sobě tři apis, která trvají dlouho: konfigurace, patients a matchings. Seznam patientů bychom mohli přidat do matchings api a tím bude stačit provolat jen api dvě. Zrychlení o třetinu.
- Kdybychom to chtěli super rychlé, chtělo by api s nějakým patients summary, které bude sloužit na vykreslení seznamu nalevo na FE a pak api pro fetchování jednotlivých pacientů, které se provolá když se na FE bude chtít zobrazit detail pacientů nebo matchingu. BE část by byla asi docela zadarmo, na FE by to vyžadovalo větší změny.
- Může se přidat indexace databáze
- Také trvá dlouho parsování hla codes, takže kvůli tomu trvají dlouho testy. To by šlo asi také zrychlit.
J

Jeste k tomu poznamky v #439 

Kouknout i na https://trello.com/c/BEqu5oPC/363-only-iterate-once-in-matchingpy-cleanup-be

**Comment by krllstdn** [comment]
Taky jsem resil tu optimalizaci v #1029. 
- ziskani txm-eventu uz netrva dlouho
- ziskani pacientu a pocitani bysme mohli spojit, ale asi nebude az tak velke zrychleni. 
- Pokud chceme ten lazy loading na frontendu tak vytvorit issue.
- Pokud chceme nejak zrychlit databazi (indexace) tak taky vytvorit issue.
Jinak tuto issue bych zavrel.
@kubantjan
