### ISSUE TITLE
Do not cacluate with patients that have parsin error

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/txmatching#568]
![image](https://user-images.githubusercontent.com/50045455/111919633-4228f600-8a8b-11eb-86ae-ac5cd58683af.png)

Dnes povolujeme vlozit pacienty takto nekompletni. Muzeme zvazit, co vsechno a jakym zpusobem vynucovat.

Chceme hazet warning pri pridani takovych pacientu plus takove pacienty nezahrnovat do vypocitaveni.

**Comment by kubantjan** [comment]
Validovat pri manualnim zadani i pres api ze vse dava smysl (ted mozna neco delame pres api, ale pres FE ne, sjednotiti a delat poradne):
- ze nam dali 1-2 hla antigen per group
- chceme pridat nejaky sanity check: Pokud to je vsechno v high res ale vsechno je >= cutoff tak dat error: hele tady vypada, ze nam davaji jen pozitivni samply. Podobne, kdyz tech antibodies bude nejak podezdrele malo. Pak taky (zas v pripade, ze jsou high res)

**Comment by kubantjan** [comment]
> ![image](https://user-images.githubusercontent.com/50045455/111919633-4228f600-8a8b-11eb-86ae-ac5cd58683af.png)
> 
> Dnes povolujeme vlozit pacienty takto nekompletni. Muzeme zvazit, co vsechno a jakym zpusobem vynucovat.
> 
> Chceme hazet warning pri pridani takovych pacientu plus takove pacienty nezahrnovat do vypocitaveni.

hazeni warningu se vyresi v #783

**Comment by kubantjan** [comment]
Myslim si, ze tohle pujde zaridit tak, ze dvojicka co ma parsing error, bude automaticky neaktivni a nepujde ani nastavit jako aktivni
