### ISSUE TITLE
Validate objects coming via API in BE via the integrated validator

### ISSUE THREAD

**Issue by tomaspavlin** [mild-blue/txmatching#589]
1) remove todo  on line 33 in file namespace.py - we will have only validation via route_utils request_body function
2) check that everywhere we are using request_body function to get object from request body (we dont do it for example in matching_api.py
3) on line 234 in error handler.py there is logger.error(f'Unexpected error code returned {error_code}, returning 500 instead') but it does not make sense there, put this logging to correct place
4) add validations to all objects we are using request_body function for. In some cases we do it (for example for patients we do not allow height negative etc. But for example for configuration we do not do that. Add the validation there as well. (use fronted or ask if you are not sure what the valid values are)

**Comment by kubantjan** [comment]
this might be related: https://github.com/mild-blue/swagger-unittest/issues/5

**Comment by krllstdn** [comment]
@kubantjan Is it necessary to create ConfigParametersDTO in CalculateFromConfig endpoint for request_body() or we can just use ConfigParameters? Because creating ConfigParametersDTO would mean code dublication.

**Comment by kubantjan** [comment]
No need :) We would just create it in case there would be some difference needed :)
