### ISSUE TITLE
Improve error logic

### ISSUE THREAD

**Issue by tomaspavlin** [mild-blue/txmatching#590]
Definujeme errory na dvou místech
- txmatching/web/web_utils/namespace.py
- error_handler.py

A obojí se propisuje do swaggeru. Tuhle duplicitu tam mít nechceme.

**Comment by abragtim** [comment]
Error responses z namespace jsou definovány jenom pro swagger?

**Comment by abragtim** [comment]
Je taková implementace v pořádku? Je změna errorů v swaggeru ekvivalentní?
