### ISSUE TITLE
Correct scoring of Other typing

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#627]
Ted other typing nebereme jako geny ale proste resime shodu vs neshodu, coz potencialne snizuje presnost v pripade ze ma nejaky pacient duplicitu v genu. Fixnout to.

**Comment by kristinagalik** [comment]
@kubantjan ak spravne chapem popisu issue toto uz je hotove nie?

**Comment by kubantjan** [comment]
Nejsem si jisty, je to tak, ze kdyz mam DPA*01:01 jiny DPA uz nemame tak si nemyslim ze pocitame DPA dvakrat tak jako treba v pripade A, nebo B muzes na to mrknout prosim? @kristinagalik
