### ISSUE TITLE
Show parsing errors in patients detail

### ISSUE THREAD

**Issue by tomaspavlin** [mild-blue/txmatching#629]
In patient detail show the errors, wanring and infors as are shown now in the popup window.

Differentiate between the different types of severity.

Show some warning next to the pair in patient list (maybe exclamation mark?) in case there are some errors/warnings (ideally different colors for different highest warning type)

Do not allow to set the pair (donor) active in case the pair has at least one error.

**Comment by NotLubo** [comment]
Posielam náhľad. Kľudne píšte spatnú vazbu ešte to môžem upraviť do zajtra.

![image](https://user-images.githubusercontent.com/40338867/161512425-71ef4363-381b-4558-97f5-ca3966c892e3.png)

**Comment by kubantjan** [comment]
@NotLubo  jeste me zajima, jak vypada to overview a ten list samotny, jak se tam pozna, ze je problem?

**Comment by kubantjan** [comment]
tohle mi prijde jinak dobry

**Comment by NotLubo** [comment]
To práve doťahujem v tom liste budú len ikonky tie čo vidíš aj tu. A to overview riešim ako rozumne zobraziť aby to nebolo preplnené ale ab to malo nejakú výpovednú hodnotu.

**Comment by NotLubo** [comment]
![image](https://user-images.githubusercontent.com/40338867/161534794-50b93952-4580-4dd5-8cf7-5f30e5d0c716.png)
