### ISSUE TITLE
Unify Antibody and Antigen

### ISSUE THREAD

**Issue by tomaspavlin** [mild-blue/txmatching#649]
Maji vuci sobe podobny vztah jako Recipient a Donor, kteri jsou spolecne Patient. V podobnem duchu by mohly byt i tyto 2 objekty.

https://trello.com/c/RlR0vXXH/378-sjednotit-antibody-a-antigen

**Comment by kubantjan** [comment]
mrkni na to @abragtim  a zamysli se jak ti task dava smysl to zadani, muzeme pak probrat

**Comment by krllstdn** [comment]
related to #390
