### ISSUE TITLE
Specify ciphers

### ISSUE THREAD

**Issue by tomaspavlin** [mild-blue/txmatching#653]
Specifikovani sifer, ktere BE podporuje: https://trello.com/c/MSoFk4Yh/419-be-specifikovani-sifer-ktere-be-podporuje

**Comment by krllstdn** [comment]
nemam pristup na trello, proto nevim o vem tu jde

**Comment by kubantjan** [comment]
Specifikovat sifrovani, ktery pouzivame nekam do dokumentace. A obecne zabezpeceni. Ale to bych nedelal vzhledem k tomu, ze overovani uzivatelu jeste budeme predelavat
