### ISSUE TITLE
Fix build warnings

### ISSUE THREAD

**Issue by tomaspavlin** [mild-blue/txmatching#658]
Chceme projít warningy při buildu FE a BE a každý buď vyřešit nebo někam sepsat, s jakými warningy jsme v pohodě a proč. 

https://trello.com/c/VSFsuKeM/400-vyresit-vsechny-warningy-pri-buildu

**Comment by kubantjan** [comment]
@abragtim mozna ze je tohle uplne obsolete, mrnout jestli se to deje a pripadne poresit

**Comment by kristinagalik** [comment]
co sa tyka toho cli tak moj guess je taky ze to chce byt globalne aby to asi bolo pristupne z komand linu a tym padom sa to dalo pouzivat na generovanie swagger filu (ale neviem mozno by to fungovalo aj keby len lokalne to bolo)

co sa tyka `npm install` asi je dobry rule of the thumb neinstalovat veci globalne aj ked to zas az tak hrozne neni ak to je len pre tu neprod verziu (?, no clue), neviem preco to riesi zrazu tie problemy ale ja ked u seba buildujem fe tak tam vidim 4 kriticke veci co by bolo dobre vyriesit.. co je tiez asi dobry dovod preco to neriesit cez -g flag, lebo stracame do buducna potencialne info o kritickych vulnerabilities

dalsia vec co asi neni najspolahlivejsia imo robit je to riesit cez `npm audit fix` lebo to vie potencialne introducnut uplny chaos.

**Comment by abragtim** [comment]
> Řekl bych, že při buildu BE nejsou důležité warningy. Jenom při tvoření env přes condu po instalaci pip dependencies máme hodně zprav, že Requirement already satisfied. Ale to asi souvisí s tím, že jsme už hodně prostě těch knihoven nainstalovali přes condu, které se snaží nainstalovat přes pip, protože potřebují to pro svou práci. Na konci vidíme zprávu "Successfully installed Bcrypt-Flask-1.0.2 aniso8601-9.0.1 attrs-22.1.0 flask-restx-1.0.3 jsonschema-4.17.3 mip-1.14.0 openapi-schema-validator-0.2.3 openapi-spec-validator-0.4.0 pdfkit-1.0.0 psycopg2-binary-2.9.5 pylint-flask-0.6 pylint-flask-sqlalchemy-0.2.0 pylint-plugin-utils-0.7 pyrsistent-0.19.2 sqlparse-0.4.3 swagger-unittest-0.3.5 tabulate-0.9.0 yoyo-migrations-7.3.2", což znamená, že všechny knihovny, které jsme chtěli nainstalovat přes pip, jsou instalovány úspěšně, a proto není potřeba to Requirement already satisfied nějak řešit.
> 
> Ohledně FE, jsou tam při "npm install" errory spojeny s tím, že nemá přistup k souboru package-lock.json. To se náhodně vyřeší přidáním vlajky -g, tj.
> 
> ```
> npm install -g
> ```
> 
> Ale budu hodně kecat, jestli úplně chápu, co se tam děje, a proto bych poprosil @kristinagalik podívat se na to. Je to safe? Vidím, že to tak děláme (s tím globalem -g) u openapi-generator-cli a Angular:
> 
> ```
> npm install -g @angular/cli
> ```
> 
> ```
> npm install -g @openapitools/openapi-generator-cli
> ```
Update k tomuto

Přistup k package-lock.json celou dobu byl. Prostě jsem musel přejít do frontend složky. 
Všechny errory se podařilo vyřešit ne přes -g, ale updatem do aktuální verzi. Doufám, že jsem update těch FE dependencies udělal správně.
