### ISSUE TITLE
Calculate max number of possible matchings

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#684]
Matemathical task:

find upper bound on number of possible different matchings depending on the number of patients.

https://trello.com/c/qwUe2Cni/187-txm-spocitat-absolutni-pocet-moznych-transplantaci-4-biomed

**Comment by krllstdn** [comment]
kde by se todle mohlo pouzit? a jak by se todle mohlo spocitat?

**Comment by kubantjan** [comment]
pri nejaky marketing prezentaci, ale ted to fakt neni podstany. zaviram
