### ISSUE TITLE
Split computation endpoint to multiple endpoints

### ISSUE THREAD

**Issue by tomaspavlin** [mild-blue/txmatching#716]
Endpoint pro výpočet matchingů teď funguje ve 3 krocích:

1. uložení konfigurace
2. vypočítání matchingů
3. vrácení matchingů

V tomto issue cheme rozdělit endpoint na výpočet na 3 enpointy.

## 1. endpoint
- uloží konfiguraci a vrátí configuration id a pokud jsou pro tuto konfiguraci už vypočítané matchingy, tak i rovnou pairing result id. Tenhle endpoint bude stačit volat, když uživatel změní konfiguraci. Při prvním načtení stránky nebo přepínání mezi matchingy a pacienty ne.

## 2. endpoint
- když nedostaneme pairing result id v 1. endpointu, zavoláme tenhle endpoint s config id, který vypočítá matchingy a když se to podaří, vrátí pairing result id.

## 3. endpoint
- bude mít parametr pairing result id a vrátí matchingy. V budoucnu třeba tady můžeme řešit stránkování matchingů.

**Comment by kristinagalik** [comment]
@kubantjan tato issue je stale relevantna, ale uz nie uplne up to date. zmena: endpoint 1 uz bol urobeny a funguje nezavisle od 2

**Comment by kubantjan** [comment]
Takze zbyva udelat 3. endpoint jo? me to prijde asi ok as is ted, az to k necemu budeme potrebovat tak to udelame
