### ISSUE TITLE
Change endpoint that sends configuration id

### ISSUE THREAD

**Issue by tomaspavlin** [mild-blue/txmatching#725]
Neposílat configuration id v computation endpointu, ale v configuration endpointu.

# Details

Configuration ID teď na FE posíláme v compute matchings endpointu, což je z historických důvodů. Kvůli tomu teď id neznáme, když přijdeme rovnou na stránku patients a nemůžeme ho tedy zobrazit v popisku `Showing patients for`.

Chceme z compute matchings endpointu dát config id pryč a posílat ho místo toho v configuration endpointu. Configuration endpointy teď mohou kromě parametrů vracet i celý objekt `Configuration`, ve kterém je i ID.

**Comment by kubantjan** [comment]
melo by pomoct i tomu, ze kdyz mame ze nam nedobehne vypocet a objevi xse chybova hlaska, tak se id configurace zasekne na predchozim.
