### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/txmatching#740]
Pridavani novych pacientu, Edge. Kdyz nemam oznacene okno prohlizece a mysi najedu, zobrazuje se otravny popup Add new patient pair

**Comment by kristinagalik** [comment]
Nastavit styl scrollbaru jak na messengeru (testovat na windows+edge)

**Comment by anhelina-sadovnikova** [comment]
Co bych měla udělat s pop upem "Add new patient pair"? Mám ho úplně odstranit nebo on se má objevit na nějakém jiném místě?

**Comment by tomaskourim** [comment]
![image](https://user-images.githubusercontent.com/50045455/184088946-9acf2348-160a-4925-9003-2161610296a6.png)

Ja bych to odstranil uplne. Pripadne se to muze objevit po najeti na tlacitko `add new`
![image](https://user-images.githubusercontent.com/50045455/184089058-8af88bdc-8637-446d-99f1-3f4942474c1f.png)

Ale asi to neni nutne. Necham na tvem uvazeni.

**Comment by anhelina-sadovnikova** [comment]
Přidala jsem box-shadow contentu a situace se zlepšila, ale za mně to řešení ještě pořád není perfektní. Mám udělat pull request tohoto nebo bude lepší zkusit něco jiného? 
<img width="960" alt="před" src="https://user-images.githubusercontent.com/110482666/185364238-d382d2fc-9cb4-44f5-8ae7-87e85dacb079.png">
<img width="960" alt="po" src="https://user-images.githubusercontent.com/110482666/185364243-f62a22dd-f181-4316-9990-8deaaf39f2d9.png">

**Comment by anhelina-sadovnikova** [comment]
Přidala jsem box-shadow contentu a situace se zlepšila, ale za mně to řešení ještě pořád není perfektní. Mám udělat pull request tohoto nebo bude lepší zkusit něco jiného?
<img width="409" alt="pred" src="https://user-images.githubusercontent.com/110482666/185366666-d947b8f7-1f04-4082-996a-19d60cc4f389.png">
<img width="498" alt="po" src="https://user-images.githubusercontent.com/110482666/185366667-029bc8d1-40ce-4796-a3ea-1aeb6c888a5c.png">

**Comment by misslecter** [comment]
@anhelina-sadovnikova Tohle vypadá spíš jako záplata na problém, který se tam děje. Konkrétně se tam děje to, že prohlížeč softwarově ty bloky vykreslí chybně, i přesto, že jsou přesně umístěné jeden nad druhým. Chybu vidíme však jenom v dolní částí bloků, v místě zaoblení rohů. Zkus vymyslet řešení, které by zabránilo překryvu bloků v tomto místě.

**Comment by anhelina-sadovnikova** [comment]
@misslecter V divu . content jsem přidala position: relative; top: 2px, takže v podstatě content se posunul o 2px dolů a v divu .new-patient__box jsem změnila overflow: hidden na overflow: visible aby ten posun byl vidět. Výsledek vypadá takto.
<img width="731" alt="result" src="https://user-images.githubusercontent.com/110482666/185965485-b2627352-6c5a-4291-b8a5-23c33b255db6.png">

Změna na overflow: visible způsobila takový problém že když zmenším okno prohlížeče obsah jde mimo div. Na druhou stranu overflow: hidden způsobuje opačný problém- obsah není vidět.
<img width="465" alt="hidden-visible" src="https://user-images.githubusercontent.com/110482666/185967774-ab435cc4-141c-4d6c-9b48-7b9e1c9afa7d.png">

Je tohle řešení vhodné? A mám-li zkusit vyřešit problém s obsahem?

**Comment by misslecter** [comment]
@anhelina-sadovnikova preferujeme reseni, ktere idealne netvori dalsi bugy 😀 
ale dobry, je to dost orisek, dekuji, ze ses do toho pustila i tak :) nechala bych to vsak zatim byt.

Zpracuj prosím drobnou pripominku tady a dam ti approve https://github.com/mild-blue/txmatching/pull/965
