### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/txmatching#742]
Pridat anglickou pdf verzi z navodu ktery je na drive zde: https://drive.google.com/drive/folders/1YPbXXKqjzSHX843K53-HWdXN8fEnXDOI

**Comment by kubantjan** [comment]
V jakym je tohle stavu? Chceme si to davat na stranky, nebo nad tim jeste nejak iterovat? @bielovico  k tomu mel spoustu poznamek, tak nevim.

Pripadne sem pridat i AJ dokumentaci, pokud nekde je.

**Comment by kubantjan** [comment]
(i na @tomaskourim

**Comment by kubantjan** [comment]
souvis s #708

**Comment by bielovico** [comment]
Riešime v rámci tejto kartičky
https://trello.com/c/4s2LQ2Fx
Aktuálny stav: Prešiel som ja, prešiel Tom, prešiel som znova ja, teraz má znova prejsť Tom a upraviť prípadne vytvoriť nové Issues. Anglická verzia je hotová z pôvodnej verzie ale obsahuje minimálne dve malé chyby, ktoré som našiel, nechceli sme ale riešiť skôr, ako je doklepaná česká,

**Comment by kubantjan** [comment]
ten navod neni na 100% final, ale lepsi nejaky navod nez zadny.
