### ISSUE TITLE
Allow transplants with manually set positive score

### ISSUE THREAD

**Issue by tomaspavlin** [mild-blue/txmatching#745]
Nekompatibilní transplantace se teď v ILP solveru nezahrne do matchingu i když jí manuálně nastavíme score na pozitivní číslo.

**Comment by kristinagalik** [comment]
Nie som si ista ci je krajsi sposob, ale kazdy z tych solverov vyzera ze berie tie validne kombinacie odinakade. V `solver_base.py` je score_matrix ktory sa vyuziva v all_solutions_solver-i, cize by sa dal "doplnit" ten matrix a tym padom by to mohlo ist pre all_soutions_solver, no score_matrix sa nevyuziva v ilp_solveri. Tam sa da ale napr v DataAndConfigurationForILPSolver doplnit graf (`txm_configuration_for_ilp.py`, 29). No pride mi to ako trochu chaoticke riesenie, no neviem ako ho unifikovat pre oba solvery...  @kubantjan

**Comment by kubantjan** [comment]
@kristinagalik čtu to odpovím později dnes sry

**Comment by kubantjan** [comment]
Omlouvam se, az ted odpoved.

melo by to jit jeste vic low level 

na urovni scoreru.

mame tam kod:


```
    def score_transplant(self, donor: Donor, recipient: Recipient, original_donor: Optional[Donor]) -> float:
        manual_score = self._manual_donor_recipient_scores.get((donor.db_id, recipient.db_id))
        if manual_score is None:
            return self.score_transplant_calculated(donor, recipient, original_donor)
        else:
            return manual_score
```

**Comment by kubantjan** [comment]
@kristinagalik

**Comment by kubantjan** [comment]
No zni to, ze to funguje. Ja jsem na to ted taky koukal, a prijde mi to tak. Tohle issue delal @tomaspavlin 

tak ho poprosim, at na to mrkne, jestli si vzpomene o co presne slo.

Zatim to teda muzes tohle opustit. 

Jen me napada, ze jak jsi to resila, mozna z toho muze byt nejaky test, ktery by se dal pridat, pokud jsme zadny takovy nemeli?

**Comment by tomaspavlin** [comment]
Také jsem to otestoval a zdá se, že to funguje. Asi se může toto issue zavřít a když na to zas narazíme, udělat nové.
