### ISSUE TITLE
Add further soft constraints

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#761]
Ikem ma dalsi soft podminky na match, kvuli kterym by chtel ukazovat vykricnicek.

TZN, pridat logiku, ktera da upozorneni soft v pripade, ze jsou poruseny (oni si to pak manualne zakazou, kdyz se jim to libit nebude)

Tyhle parametry mit jako vlastnosti recipienta

Ma jit o:
- age
- weight
- height

v ramci tohoto issue doplnit detaily do #803

**Comment by kubantjan** [comment]
u vsech trech podminek chceme mit moznost to omezit jak shora, tak zesdola

**Comment by kubantjan** [comment]
nove objekt:

issues_with_transplant: {
message: "There were several issues with this transplant, see detail"
detailed_messages": ["Too high, "too heavy"]
}

**Comment by kubantjan** [comment]
V ramci tohoto tasku i umoznit z FE nastavit tyto paramtery (jsou to vzdycky jen recipientovy vlastnosti a mely by se pridat do jsonu ve sloupecku recipient requirements

**Comment by tomaskourim** [comment]
Ještě bych měl téma do diskuze. Nechceme tohle povolit jak lokálně (tedy pro konkrétního recipienta), tak i globálně? Třeba povolit max o 50% "větší" ledvinu. Udělat to podobně jako u toho, kdy vyžadujeme lepší CI. Ten můžeme vyžadovat globálně, ale taky i lokálně, u konkrétního pacienta.

**Comment by kubantjan** [comment]
Jasný to by bylo fajn teď bych udělal ten minimální change co si řekli ale tohle by bylo nice pak
