### ISSUE TITLE
Send parsing errors and warnings in patient detail

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#782]
I s informaci, o jakou severitu jde]

ma za vyznam dodavat data na FE

**Comment by NotLubo** [comment]
V súčastnosti sa všetky informácie posielajú cez `v1/txm-event/:txm_event_id/patients/configs/`. Takže najlepšie z hľadiska FE by bolo ak by sa ku každému pacientovy (zvlášť pre donor a reciepient ako to aj teraz je) pridal objekt ktorý by vyzeral cca takto

`{
  "allMessages": {
    "warnings": ["message", "message"],
    "errors": ["message", "message"],
    "infos": ["message", "message"],
  }
}`
