### ISSUE TITLE
SMS two factor authentication in authentic

### ISSUE THREAD

**Issue by LukasForst** [mild-blue/txmatching#795]
use sms authentication similar to the one currently in use, just change the settings a bit according to the description below.

Ucet a heslo trax zustalo stejne
Zmeny v API

1/ URL pro odeslani SMS je nyni [https://sms.ikem.cz/SendMessage](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsms.ikem.cz%2FSendMessage&data=04%7C01%7C%7C9ae46682d5684f37e03b08da08ed3917%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832112965725141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tT6k8y7drF3ljGppa80uozpffUnEypPZbRjJ50upjEo%3D&reserved=0)

2/ Vyhodil jsem GET a zustal pouze POST (parametry lze odeslat jako formular ci JSON).

4/ Jsou vyhozeny parametry cmd  (when a voice, protoze je nikdo nepouzival)

3/ Navratova hodnota HTTP/200 je ted jen pri korektim odeslani, jinak HTTP/400 ci HTTP/500 + text chyby

Zkuste, prosim, zda to vsechno projde a pokud ano, prehodte a dejte vedet

**Comment by kubantjan** [comment]
<img width="981" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/24394374/161385936-af33cf64-39c4-45fc-b693-60a4e931bf90.png">

**Comment by kubantjan** [comment]
<img width="642" alt="image (4)" src="https://user-images.githubusercontent.com/24394374/161386091-d7846031-3f1f-443c-a5be-9b625c740662.png">
