### ISSUE TITLE
Slightly blurred graphics on higher resolutions with Firefox

### ISSUE THREAD

**Issue by bielovico** [mild-blue/txmatching#799]
When viewing txm.demo.mild.blue on my built-in display with resolution 1920x1080, everything is sharp as expected, 
![image](https://user-images.githubusercontent.com/23350181/160583414-fca82c8f-9f9b-4a17-9ed8-d1d6e90e5283.png)
However when I view it on my external display with resolution 2560x1440, the overview of found matchings becomes strangely slightly blurred (je to hnusný 😄). Happens on Firefox (left), Edge (right) looks normal even on higher resolution.
![image](https://user-images.githubusercontent.com/23350181/160585756-03a175fd-10db-4631-b42b-dc2bf924f4aa.png)

**Comment by krllstdn** [comment]
obsolete. now it looks fine on firefox (tested with the same resolution)
