### ISSUE TITLE
List of matchings moved to the right and loads of errors in console

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#815]
I am not sure why this happens. See screenshot:

![Screenshot from 2022-04-05 23-34-40](https://user-images.githubusercontent.com/24394374/161854007-32ec298c-6c58-4759-ac7c-1e1fae1b1c15.png)
 
mozna souvisi s obrovskym listem erroru v consoli?

pokud ne, bylo by fajn vyresit taky:

![Screenshot from 2022-04-05 23-43-27](https://user-images.githubusercontent.com/24394374/161854770-bed851e5-aa20-49c2-9a6d-5e8673eb2c48.png)

**Comment by NotLubo** [comment]
Nesúvisí to. To prvé bude chyba flexboxu. Pracujem na oprave. Tá konzola asi súvisí s tým že ťaháme fonty od google a nemáme ich v projekte.

**Comment by NotLubo** [comment]
#817 ticket pre CSP
