### ISSUE TITLE
Virtual crossmatch in case antibodies against all broad/split antigens are present

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#856]
In case we have all anantibodies in high res AND we are in the case of broad or split match type we should be forbidding some extra transplants

in case the donor has some typization T in broad and recipient has all high res antibodies that are in broad T positive, then we should assume there was virtual crossmatch in all match types

similarily for split resolution

**Comment by kristinagalik** [comment]
@kubantjan este mam predsa len otazku:
ak je dajaky antigen v broad napr A10, a ma associated splits A25 a A26 (a v high res existuju napr A*25:01, A*25:02, A*26:01, A*26:02), a donor ma teda A10 v broad, tak na to aby som to pridala do positive matches tak musi mat recipient napr A*25:01, A*26:01, alebo vsetky 4 antigeny?

**Comment by kubantjan** [comment]
Chceš aby prostě všechny s broad A10 byly positive aby byl crossmatch high res Když alespoň jeden negative tak bude crossmatch broad. @kristinagalik
