### ISSUE TITLE
Ensure that cross blood group tranplant is visible in black and white

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#857]
Both in report and on the web the distinction between normal blood group transplat and cross blood group is just shade of grey and that is not well distinguishable in black and white print.

Propose some better way.

**Comment by kristinagalik** [comment]
@kubantjan 

je toto ok? 
![Screenshot_20220606_153653](https://user-images.githubusercontent.com/56656359/172187751-d2c8fc06-fcf6-4886-a462-53d3beb45b26.png)

**Comment by kubantjan** [comment]
To mi prijde malo vyrazny,

zkusil bych tam asi pridat nejaky jeste symbol dalsi nebo neco. 

Nevim kam? Vedle toho barevnyho skore? Treba 'x' ?

da se zkusit vygooglit jestli "pres krevni skupinu nejak neni symbilizovany"

Zkusim na to poslat mejl do ikemu jestli pro to neco nemaji. Dam te do kopie

**Comment by kubantjan** [comment]
Z IKEM napsali: Tady to značíme AB0i TX.

Tak možná „i“ –  jako inkompatibilní?


vlastne me napada, ze nejlepsi smysl ma si hrat s tim symbolem ">" ktery znazornuje to darovani. 
tak me napada mozna zmenit ten symbol ">" na neci jako "i>" nebo tak neco?

**Comment by kubantjan** [comment]
Plus mozna do hlavicky detailu primo napsat AB0i
