### ISSUE TITLE
Increase python version to 3.10.5

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#888]
should ensure that everything works on m1, now openssl package raises an error when running the project locally.

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/40338867/177271579-0bb77130-7f01-452b-b24c-e42a2d932ee9.png">

https://github.com/pyca/pyopenssl/issues/873#issuecomment-1014069883

**Comment by jpzhangvincent** [comment]
Hmm I upgraded to python 3.10.5 in my conda environment but I still got the "memory error". Any ideas?

**Comment by kubantjan** [comment]
Hello @jpzhangvincent!

 could you tell us for which purposes you want to use the tool? We would be happy to get in touch!
 
 regarding the memory error issue. We need more information about it. When exactly it happens, stacktrace of the error etc. Without that we cannot help.
