### ISSUE TITLE
Use oauthlib with authentik

### ISSUE THREAD

**Issue by NotLubo** [mild-blue/txmatching#895]
We have decided to use authentik with oauth2 to authenticate users.

For that purpose we need our system to work with oauth2.

It seems (but I am not 100% sure) that the best library will be https://github.com/lepture/flask-oauthlib try to use that library to communicate and work with authentik. Replace the current AuthentikLogin with something from this library and try to set it up.

Hopefully it should be quite straight forward..

**Comment by kubantjan** [comment]
@NotLubo  please more information.

**Comment by NotLubo** [comment]
Authentic now sends auth token and refresh token to BE which sends it to FE. BE should also store auth token so it can verify user when API call is made.

authtoken, refreshtoken table should be created in DB
