### ISSUE TITLE
Add User groups in authentic

### ISSUE THREAD

**Issue by NotLubo** [mild-blue/txmatching#896]
Add user groups to authentik as are in current version, plus add there txm_events the user has rights for to scopes.

This task is mostly about understanding how group of a user and txm_Events will be sent to backend plus how they can be setup. 

This task is probably mostly going to be about readme update. IT should provide clear path for #892

**Comment by kubantjan** [comment]
@NotLubo  doplnis sem vice informaci?

**Comment by kubantjan** [comment]
- understand how attributes of users and groups and groups within groups work. 
- what is super user
- final proposal how to current functionality can be imitated in authentik
