### ISSUE TITLE
Improvements from testing

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#919]
3) tenhle case by to melo ukazovat 

"undecidable" pro DQA1 protilatky ne?
![Screenshot from 2022-07-15 18-00-20](https://user-images.githubusercontent.com/24394374/179262033-6949b2d9-cc95-4bd8-9147-c4c480f6da9f.png)

zaclo to fungovat az kdyz jsem odebral vsechny z other a pak se tam zas objevily obe ty skupiny i warning:

![Screenshot from 2022-07-15 18-05-44](https://user-images.githubusercontent.com/24394374/179262815-4169081d-7d38-455a-b81e-7bc21cfa0bcb.png)

4) bridging donor neni ab0i 

![Screenshot from 2022-07-15 18-02-26](https://user-images.githubusercontent.com/24394374/179262345-285814a2-a36b-4f29-929d-7fd761e72838.png)

5) Alter match type logic further
- typization in split a ALL antibodies in high res positive for this split ->  currently crossmatch_level high_Res_wtih_split, newly high_Res
- typization in split and SOME antibodies in high res positive for this split -> currently crossmatch level split, newly high_res_with_split

**Comment by kristinagalik** [comment]
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6

**Comment by kubantjan** [comment]
5.yep for broad as well @kristinagalik

**Comment by kubantjan** [comment]
2. I am not sure what is the best way to deal with that. But am sure the current is not the best

**Comment by kubantjan** [comment]
2. I am not sure what is the best way to deal with that. But am sure the current is not the best

About 3. Yep maybe.. try to create such issue I will comment there if I agree
