### ISSUE TITLE
Try to get all the different types of crossmatches in the app

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#921]
Test the app and txm.stg.mild.blue.
- Add new txm event called "mixed_resolution_with_crossmatch_types"
- Add there couple of patients (either via generator or manually, just around 4,5 should be enough)
- Alter the antibody and typization data so all the different types of crossmatches are shown there in the first found matching

Tips on how to:
- credentials are in bitwarden
- to create the txm event you have to use an endpoint directly (it is not implemented in FE)

when you do this successfully improve generator to generate also mixed resolution data where all those cases occur.

**Comment by krllstdn** [comment]
@kubantjan so, I need to create a test?

**Comment by kubantjan** [comment]
@krllstdn  this task has two parts:

1) do it manually in stg after that tell me, I will have a look 
2) improve the generator as I write above so that you can easily generate such event that you have created manually with a generator.
