### ISSUE TITLE
Different warning flag if all warnings confirmed

### ISSUE THREAD

**Issue by kristinagalik** [mild-blue/txmatching#923]
If all warnings are confirmed the flag in the list of patient should be different than if warnings are unconfirmed

**Comment by kubantjan** [comment]
The first sentence is not true:
![Screenshot from 2022-07-18 17-31-13](https://user-images.githubusercontent.com/24394374/179547390-85fe134a-a883-454c-88ab-6f6dc506ed85.png)

**Comment by kristinagalik** [comment]
> The first sentence is not true:
> ![Screenshot from 2022-07-18 17-31-13](https://user-images.githubusercontent.com/24394374/179547390-85fe134a-a883-454c-88ab-6f6dc506ed85.png)

Sorry this was meant for Matchings page not Patients page
