### ISSUE TITLE
Confirm warning and then click save - not intuitive behaviour

### ISSUE THREAD

**Issue by kristinagalik** [mild-blue/txmatching#924]
when clicking on confirm warning and then clicking save even though nothing about the patient was changed, the patient refreshes anyway and the warnings are uncofirmed again. IT is not intuitie that one does not have to click on seve to store warning confirmation

**Comment by krllstdn** [comment]
@kubantjan I see that you closed the PR that was trying to solve that. This thing is really not intuitive. Should it be solved?

**Comment by kubantjan** [comment]
yes it should but it is not high priority. I guess it is about improvement of FE design only.

**Comment by kubantjan** [comment]
I moved to #317
