### ISSUE TITLE
Better square bracket antibody parsing

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#928]
When an antibody in square bracket (i.e. DP[01:01,02:02]) is being parsed it is first split in function preprocess_hla_code_in into two antibodies and then processed separately.

preprocess_hla_code_in should newly return antibody with its paired antibody. not just a string.

**Comment by kristinagalik** [comment]
znamena to "antibody with its paired antibody. not just a string." ze mam returnovat tuple antibody objektov? alebo tuple stirngov?

**Comment by kubantjan** [comment]
No zatím se vracel jen string tak teď si v představuju objekt parsed raw antibody. Kterej bude mít dvě věci

Hla_code_raw

A secondary hla code raw což bude ten druhý kód do na počtu.
