### ISSUE TITLE
Copy patients between txm events not working

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#956]
When I am copying all patients from txm_Event 2 on staging to txm_event 1 on staging the copying fails with:

There were the same donors in current data and in the data for upload: {'140B-IND-R'}

but the txm_event_1 is empty, so it makes no sense, the copying should go through successfully. 

I try to send the put request with all ids of all donors in the event. 

body of the request that is failing is below:

{
  "txm_event_id_from": 2,
  "txm_event_id_to": 1,
  "donor_ids": [32,
    12,
    5,
    1,
    2,
    3,
    4,
    13,
    6,
    7,
    8,
    9,
    10,
    11,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    31,
    33,
    34,
    35,
    36,
    37,
    38,
    30,
    110,
    111
  ]
}

**Comment by kubantjan** [comment]
There are 3 issues:
1) if there is a patient with multiple donors in the originial event that one wants to copy an error There were the same donors in current data and in the data for upload: {'140B-IND-R'} is raised. Fixed that in such a way that even such patients are copied
2) in case there is a donor in the list of donors to copy that is not from the original event the endpoint returns 
There were the same donors in current data and in the data for upload: {'140B-IND-R'}
{
  "error": "Invalid request data.",
  "message": "30"
}

fix that to be more informative
3) for donor with id 30 at staging the copying does not work. We do not know why fix that 

{
  "txm_event_id_from": 2,
  "txm_event_id_to": 1,
  "donor_ids": [
    30

  ]
}

**Comment by kristinagalik** [comment]
@krllstdn 

maybe its sufficient to make a dictionary for recipients {old_id: new_id} so when you are adding a new one you can check whether it was added previously, and if yes, just update "related_recipient_id" to the new_id for the new donor and add the donor
