### ISSUE TITLE
Make AllSolutionsSolver handle correctly mutliple donors

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#961]
At the moment there can be cycles in all solutions solver that contain two donors with the same recipient probably. Check that. And check whether there is not some other issue with multiple donors in this solver.

If there is only the issue I mention above fix it. Try to do poor man's solution for the moment: filter the cycles that would contain invalid set of patients.

**Comment by krllstdn** [comment]
We with @kristinagalik checked it and it handles multiple donors correctly.
