### ISSUE TITLE
Optimize the size of report

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#964]
We need the report to have a size that is possible to send via email. I.e. under 5mb even in case there is many matchings and around 50 pairs. At the moment the size of report is > 30  Mb 

Look into how to decrese this (it might mean losing some nice graphics) but mostly there might be loads of suboptimal pdf generation there)

**Comment by krllstdn** [comment]
@kristinagalik When I generate a report from stg server I get a report of size 36Mb. When I generate a report locally with a larger number of matchings and larger number of pairs (128 pairs and 10 matchings, while on stg server 60 pairs and 5 matchigns) I get a report with size 7Mb. In both cases patient section is enabled.
What is unclear to me how is that possible? Why the same code generates files with different sizes?
