### ISSUE TITLE
Load spanish data to TXM

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#967]
Take the HLA data, use either the data ouput from fruszina script or even better use the original data, run fruszinas script (maybe udpate it a bit) and write a script that process fruszinas ouput into our json

**Comment by kubantjan** [comment]
Next step is an email to Fruszi and Peter

**Comment by kubantjan** [comment]
Kristina and Fruszina will look into the data and add questions for the call of PEter on 23.9.

**Comment by kubantjan** [comment]
remind with the question about whom to send the data export

**Comment by kubantjan** [comment]
Kristina will send to kristof export of loaded spanish txm event so he can try to run the optimizer on them

**Comment by kubantjan** [comment]
Waiting for the answer about the HLA questions from ONT

**Comment by kristinagalik** [comment]
TODO: get rid of problems with hla parsing for spanish data and use them as an input to the hungarian solver before rotterdam meeting

**Comment by kristinagalik** [comment]
try to run with all solution solver

**Comment by kubantjan** [comment]
@kristinagalik  update: increse max_cycles_in_all_solutions_solver and see whether it helps

**Comment by kubantjan** [comment]
Before spanish data will work issue #1038

**Comment by kubantjan** [comment]
done, cekame na odpoved petera.

**Comment by kubantjan** [comment]
freezed, uvidime, jestli jeste neco nebude treba, az se elisabeth ozve

**Comment by kubantjan** [comment]
ceka na zmeny v #1113

**Comment by kristinagalik** [comment]
update: vytvorila som novy event na deme: "DEMO_SPANISH_DATA", uploadla spanielske data, a pridala Peterovi Birovi tento event ako allowed

**Comment by kubantjan** [comment]
@kristinagalik  a dala jsi peterovi vedet? je to timto done?

**Comment by kubantjan** [comment]
Cekame az se Peter Biro ozve,  ze vse rozumi a je ok, a pak zavrem, kdyz se do 7.2. neozve, tak se @kristinagalik  popta jestli je vse ok.
