### ISSUE TITLE
Double text in the button "Set configuration as default"

### ISSUE THREAD

**Issue by krllstdn** [mild-blue/txmatching#973]
If a configuration differs from the default, there's a button "set configuration as default". When it is clicked there's double text. As  can be seen in the images:

![Image](https://user-images.githubusercontent.com/50211831/185636141-7a0584f6-d85d-4b23-9ce4-d0570545c461.png)

![Image](https://user-images.githubusercontent.com/50211831/185635197-5bcffa59-01fc-4bfb-a558-9803ce0a5d69.png)

**Comment by kristinagalik** [comment]
@krllstdn je toto este stale relevantne? mne to to tak neukauzje

**Comment by krllstdn** [comment]
@kristinagalik pred chvyli jsem to vyzkousel a jo, uz se to nestava..
