### ISSUE TITLE
Generating report raising errors

### ISSUE THREAD

**Issue by kristinagalik** [mild-blue/txmatching#978]
error message is not descriptive enough

(this i couldnt replicate again, probably forgot what exactly i did or for which event i did it, but i remember setting number of matchings in configuration to max and then including extra 20 matchings in report, but i dont think this should raise error..)
![Image](https://user-images.githubusercontent.com/56656359/186616546-74d84758-b648-405e-8bf7-3b9d8144ddd7.png)

(when i set number of matchings besided selected matching to be included to something greater than 20)
![Image](https://user-images.githubusercontent.com/56656359/186615883-a9a2f386-c8c2-42d4-8f5d-8adf44495bc7.png)

**Comment by kubantjan** [comment]
@krllstdn this is still happening? If yes please have a look into that and fix it :)

**Comment by krllstdn** [comment]
@kubantjan no, it doesn't happen anymore
