### ISSUE TITLE
Corners are not touching as they should be in UI

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/txmatching#981]
Rohy nelicuji

![image](https://user-images.githubusercontent.com/50045455/135671067-7530d3fe-c1f7-43b7-9cb5-cf7b05a2f6d4.png)

**Comment by krllstdn** [comment]
uz to skoro neni videt


![Image](https://user-images.githubusercontent.com/50211831/206451454-0b8d3d7d-a4a8-4d15-9c99-ee42d5927175.png)
