### ISSUE TITLE
Dont use score matrix, just compatibility graph

### ISSUE THREAD

**Issue by kristinagalik** [mild-blue/txmatching#995]
There is currently used `score_matrix` in several places in the code, and it contains also information about negative scores (meaning incompatible pairs). 

This could be all replaced by a compatibility graph which contains only non-negative values (as a dictionary or list of objects for instance)

**Comment by kubantjan** [comment]
vic popisu co to znamena.

**Comment by kristinagalik** [comment]
@kubantjan tak moze byt?

**Comment by kubantjan** [comment]
@kristinagalik  yop, vesele na to
