### ISSUE TITLE
Make optimizer module schema consistent with the hungarian one

### ISSUE THREAD

**Issue by kristinagalik** [mild-blue/txmatching#998]
Right now, there are three versions of compatibility_graph schema. 

There is the hungarian one that looks like this: (the hungarians have created optimizer module too, this is their input schema, we should expect the same input so the modules are interchangable)
List of dictionaries, where each dictionary is composed of donor_id: int, recipient_id: int, weights: Dict[str, int]
Should look something like this:
```
class CompGraphEntry:
    donor_id: int
    recipient_id: int
    weights: Dict[str, int]

class SomeInputObject:
    ...
    compatibility_graph: List[CompGraphEntry]
    ...
```
Example of the compatibility graph:
```
"compatibility_graph":[
    {
        "donor_id":1,
        "recipient_id":4,
        "weights": {
            "waiting_time":30.29,
            "sensitisation":20
        }
    },
    {
        "donor_id":3,
        "recipient_id":2,
        "weights": {
            "waiting_time":40,
            "sensitisation":60.92
        }
    },
    {
        "donor_id":5,
        "recipient_id":2,
        "weights": {
            "waiting_time":10,
            "sensitisation":20
        }
    }
],
```
Then there is the Txm version that looks like this:
`CompatibilityGraph = Dict[Tuple[int, int], int]` that basically has the tuple (donor_id, recipient_id) as a key referring to the weight. Can be found in `compatibility_graph.py`

Then there is the optimizer module compatibility graph, can be found in `optimizer_funcitons` in `get_compatibility_graph_for_optimizer_api` and it is similar to the hungarian one, except the "weights" entry. So it looks like this:
```
"compatibility_graph":[
    {
        "donor_id":1,
        "recipient_id":4,
        "waiting_time":30.29,
        "sensitisation":20
    },
    {
        "donor_id":3,
        "recipient_id":2,
        "waiting_time":40,
        "sensitisation":60.92
    },
    {
        "donor_id":5,
        "recipient_id":2,
        "waiting_time":10,
        "sensitisation":20
    }
],
```

It would be great to have the optimizer module comp_graph, txmatching comp_graph (and the hungarian one if possible, or else just expect the same input schema to the optimizer module and parse it accordingly to the new schema) having same structure: Dict[Tuple[int, int], Dict[str, int]], where the Tuple[int, int] is (donor_id, recipient_id) and Dict[str, int] are the weights

**Comment by kubantjan** [comment]
@kristinagalik  now the description looks good. Thx!

**Comment by krllstdn** [comment]
@kristinagalik In the issue name is written that  we need to change Optimizer Module Compatibility Graph Schema so that it looks like the Hungarian one and the same is written in the beginning of issue description. But at the end of issue description you say that all three schemes should have the same structure: Dict[Tuple[int, int], Dict[str, int]] which is a mix of the Hungarian one and the TXM one. I'm a bit confused. What exactly should be done?
Just to merge three  schemes into one  mentioned at the end and refactor code with respect to that? Or make the TXM compatibility graph look like the Hungarian one?

**Comment by krllstdn** [comment]
@kubantjan it was answered in a call

**Comment by kubantjan** [comment]
> @kubantjan it was answered in a call 

I don't care where it was answered but the conclusion should be here because I was not in the call and I cannot check whether the issue was done if I don't know what was supposed to be done

**Comment by krllstdn** [comment]
@kubantjan sorry, I thought your approval meant that you understand Kristina's description.
I asked for some clarification and what had to be done is: to update existing `compatibility_graph`, create new compatibility graph specifically for optimizer api, update optimizer api entry object - all with respect to Hungarian data format
